### ISSUE TITLE
Fatal ARCore native exception when setting up augmented image database in emulator

### ISSUE THREAD

**Issue by JGregoryAtiba** [google-ar/sceneform-android-sdk#1003]
Our app is crashing on the emulator when we try to configure an augmented images database.  (Works fine on physical device).  I've tried both loading the database from a .imgdb file and creating it manually in code.  I've found that when I instantiate the database directly in code but don't add any images to it, there's no crash.  But, if I add an image to the database, the crash occurs.

Running on Pixel 2 Emulator, API 27 (Google Play) with Google_Play_Services_for_AR_1.15_x86_for_emulator.apk.  Other AR features (camera view, adding nodes) have been working fine.

Code snip:
```
Config config = new Config(session);
config.setUpdateMode(Config.UpdateMode.LATEST_CAMERA_IMAGE);
AugmentedImageDatabase augmentedImageDatabase = new AugmentedImageDatabase(session);

Bitmap bitmap;
String filename = "my-image.jpg"
try (InputStream inputStream = getAssets().open(filename)) {
    bitmap = BitmapFactory.decodeStream(inputStream);
} catch (IOException e) {
    Log.e(TAG, "I/O exception loading augmented image bitmap.", e);
    return;
}

// Commenting out this line prevents the crash:
augmentedImageDatabase.addImage(filename, bitmap, 0.235f);

// Commenting out this line also avoids the crash:
config.setAugmentedImageDatabase(augmentedImageDatabase);

session.configure(config);
sceneView.setupSession(session);
```

Logcat:
```
2020-03-04 10:03:45.143 26416-26416/com.skwids I/native: planar_target_tracking_manager.h:111 Config of PlanarTargetTrackingManager:
    -pose_refinement_with_detection_interval_ns: 0
    -min_interval_between_detections_ns: 500000000
    -filter_parallax: false
    -filter_result: true
    -multiple_targets: true
    -mini_detection: true
    -tracking_mode: 1
2020-03-04 10:03:45.146 26416-26416/com.skwids E/native: camera_config_manager_updated.cc:559 UpdatedBugFixes on CameraConfigManagerUpdated is unimplemented!
2020-03-04 10:03:45.147 26416-26416/com.skwids E/native: camera_config_manager_updated.cc:559 UpdatedBugFixes on CameraConfigManagerUpdated is unimplemented!
2020-03-04 10:03:45.147 26416-26416/com.skwids I/third_party/arcore/ar/core/android/sdk/arimage_jni.cc: Loading AImage symbols
2020-03-04 10:03:45.148 26416-26416/com.skwids I/third_party/arcore/ar/core/android/sdk/image_metadata_jni.cc: Loading ACameraMetadata symbols
2020-03-04 10:03:46.637 26416-26416/com.skwids I/native: cpu_feature_extractor.cc:90 Extracting FREAK descriptors.
2020-03-04 10:03:46.646 26416-26416/com.skwids I/native: device_provider.cc:1811 Identified device type: kEmulator
2020-03-04 10:03:46.657 26416-26416/com.skwids I/native: session.cc:928 Entering Session::Resume.
2020-03-04 10:03:46.657 26416-26604/com.skwids I/native: android_camera.cc:755 [Camera=0; State=CLOSED] Reset cleanly got to CLOSED state.
2020-03-04 10:03:46.658 26416-26416/com.skwids I/native: pursuit_tracker.cc:1330 AugmentedRegion config changed, enabled:1, quad:true, downsample:true, global reacquisition:false, lite mode:false, adaptive frame delay:false, interpolation:true
2020-03-04 10:03:46.667 26416-26620/com.skwids W/native: motion_analysis_calculator.cc:370 No input video header found. Downstream calculators expecting video headers are likely to fail.
2020-03-04 10:03:46.668 26416-26416/com.skwids I/CameraManagerGlobal: Connecting to camera service
2020-03-04 10:03:46.673 26416-26416/com.skwids I/native: session.cc:2481 Update Frame Delay to 3 frames.
2020-03-04 10:03:46.673 26416-26416/com.skwids I/native: android_sensors.cc:150 Starting thread.
2020-03-04 10:03:46.674 26416-26416/com.skwids I/native: cameras.cc:1106 Selected camera 0 stream 0 as feature extraction stream.
2020-03-04 10:03:46.674 26416-26625/com.skwids I/native: android_sensors.cc:28 Gyro min delay 10ms requesting 10ms
2020-03-04 10:03:46.674 26416-26416/com.skwids I/native: logger.h:28 DataSourceMetrics: kStartImageSubSystem: 150.253us
2020-03-04 10:03:46.675 26416-26416/com.skwids I/native: session.cc:1081 Session::ResumeWithAnalytics returning OK.
2020-03-04 10:03:46.677 26416-26604/com.skwids E/NdkImageReader: AImageReader_getWindow
2020-03-04 10:03:46.678 26416-26625/com.skwids I/native: android_sensors.cc:28 Accel min delay 10ms requesting 10ms
2020-03-04 10:03:46.705 26416-26416/com.skwids E/native: camera_config_manager_updated.cc:559 UpdatedBugFixes on CameraConfigManagerUpdated is unimplemented!
2020-03-04 10:03:46.706 26416-26416/com.skwids I/native: session.cc:928 Entering Session::Resume.
2020-03-04 10:03:46.706 26416-26416/com.skwids I/native: session.cc:961 Session::ResumeWithAnalytics returning OK.
2020-03-04 10:03:46.706 26416-26604/com.skwids I/native: logger.h:28 CameraMetrics: OpenCamera: 12.985144ms
2020-03-04 10:03:46.706 26416-26604/com.skwids I/native: camera_ndk_wrapper.cc:25 Loading Android NDK 28 symbols from libcamera2ndk.so
2020-03-04 10:03:46.713 26416-26604/com.skwids E/native: camera_ndk_wrapper.cc:42 Unable to load ACameraDevice_createCaptureSessionWithSessionParameters
2020-03-04 10:03:46.720 26416-26604/com.skwids I/native: logger.h:28 CameraMetrics: CreateCaptureSession: 5.78923ms
2020-03-04 10:03:46.722 26416-26604/com.skwids I/native: capture_request_utils.cc:193 Flash: ConfigureRequestFlashMode - OFF
2020-03-04 10:03:46.724 26416-26600/com.skwids I/native: cameras.cc:1258 Camera 0 changed state CLOSED->OPEN; Camera device opened successfully. i=0
2020-03-04 10:03:46.724 26416-26600/com.skwids I/native: cameras.cc:1258 Camera 0 changed state OPEN->CAPTURING; Started capture session. i=1
2020-03-04 10:03:46.802 26416-26416/com.skwids D/EGL_emulation: eglCreateContext: 0x84def800: maj 3 min 0 rcv 3
2020-03-04 10:03:46.802 26416-26416/com.skwids E/EGL_emulation: tid 26416: eglMakeCurrent(1542): error 0x3009 (EGL_BAD_MATCH)
2020-03-04 10:03:46.802 26416-26416/com.skwids E/libEGL: eglMakeCurrent:1062 error 3009 (EGL_BAD_MATCH)
2020-03-04 10:03:46.806 26416-26416/com.skwids E/native: session.cc:1827 Invalid ray produced by view data!
2020-03-04 10:03:47.117 26416-26626/com.skwids I/native: timebase_helpers.cc:168 Timebase offset intialized to 0
2020-03-04 10:03:47.117 26416-26628/com.skwids I/native: logger.h:28 DataSourceMetrics: kFirstGlCallback: 443.512063ms
2020-03-04 10:03:47.124 26416-26629/com.skwids I/native: logger.h:28 CameraMetrics: FirstCaptureComplete: 401.862541ms
2020-03-04 10:03:47.124 26416-26626/com.skwids I/native: logger.h:28 DataSourceMetrics: kFirstImageCallback: 450.100906ms
2020-03-04 10:03:47.124 26416-26626/com.skwids E/ACameraMetadata: getConstEntry: cannot find metadata tag 65576
2020-03-04 10:03:47.124 26416-26626/com.skwids E/ACameraMetadata: getConstEntry: cannot find metadata tag 65578
2020-03-04 10:03:47.131 26416-26620/com.skwids W/native: motion_analysis_calculator.cc:791 Requested image format in RegionFlowComputation does not match video stream format. Overriding.
2020-03-04 10:03:47.132 26416-26620/com.skwids I/native: region_flow_computation.cc:616 Instantiating and using NEON optimized non-OpenCV KLT.
2020-03-04 10:03:47.138 26416-26626/com.skwids E/ACameraMetadata: getConstEntry: cannot find metadata tag 65576
2020-03-04 10:03:47.143 26416-26611/com.skwids W/native: imu_integrator_utils.cc:39 Gyro samples do not cover << [ 0 ; 15309421060000 ] nanosecond. Use identity R. Gyro samples cover [ 15309060054000 ; 15309500039000 ] nanosecond.
2020-03-04 10:03:47.143 26416-26620/com.skwids I/native: motion_analysis_calculator.cc:618 Analyzed frame 1
2020-03-04 10:03:47.145 26416-26620/com.skwids W/native: parallel_invoker.h:300 Unsupported invoker mode selected on Android. Falling back to ThreadPool
2020-03-04 10:03:47.150 26416-26416/com.skwids E/ACameraMetadata: getConstEntry: cannot find metadata tag 65576
2020-03-04 10:03:47.151 26416-26416/com.skwids E/EGL_emulation: tid 26416: eglMakeCurrent(1542): error 0x3009 (EGL_BAD_MATCH)
2020-03-04 10:03:47.151 26416-26416/com.skwids E/libEGL: eglMakeCurrent:1062 error 3009 (EGL_BAD_MATCH)
2020-03-04 10:03:47.162 26416-26416/com.skwids E/EGL_emulation: tid 26416: eglMakeCurrent(1542): error 0x3009 (EGL_BAD_MATCH)
2020-03-04 10:03:47.162 26416-26416/com.skwids E/libEGL: eglMakeCurrent:1062 error 3009 (EGL_BAD_MATCH)
2020-03-04 10:03:47.165 26416-26626/com.skwids E/ACameraMetadata: getConstEntry: cannot find metadata tag 65576
2020-03-04 10:03:47.166 26416-26416/com.skwids E/native: error_policy_util.cc:260 
    ################ ARCore Native Error ##################
    BUILD_CHANGELIST:292460638
    BUILD_BASELINE_CHANGELIST:290669628
    ################### Stack Trace Begin ################
    ARCoreError: third_party/arcore/ar/core/android/implementation/android_frame_manager_gl.cc:204	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/android/implementation/android_frame_manager_gl.cc?g=0&l=204
    ARCoreError: third_party/arcore/ar/core/frame_manager.cc:344	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/frame_manager.cc?g=0&l=344
    ARCoreError: third_party/arcore/ar/core/frame_manager.cc:144	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/frame_manager.cc?g=0&l=144
    ARCoreError: third_party/arcore/ar/core/session.cc:1351	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/session.cc?g=0&l=1351
    ARCoreError: third_party/arcore/ar/core/c_api/session_lite_c_api.cc:63	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/c_api/session_lite_c_api.cc?g=0&l=63
    ################### Stack Trace End #################
2020-03-04 10:03:47.170 26416-26416/com.skwids D/AndroidRuntime: Shutting down VM
2020-03-04 10:03:47.174 26416-26621/com.skwids W/native: tracking.cc:3753 Feature descriptors not exist
2020-03-04 10:03:47.174 26416-26621/com.skwids W/native: box_detector.cc:180 Detection skipped due to empty features or descriptors.
2020-03-04 10:03:47.174 26416-26621/com.skwids W/native: tracking.cc:3753 Feature descriptors not exist
2020-03-04 10:03:47.174 26416-26621/com.skwids W/native: box_detector.cc:180 Detection skipped due to empty features or descriptors.
2020-03-04 10:03:47.177 26416-26416/com.skwids E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.skwids, PID: 26416
    com.google.ar.core.exceptions.FatalException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:143)
        at com.google.ar.core.Session.nativeUpdate(Native Method)
        at com.google.ar.core.Session.update(Session.java:67)
        at com.google.ar.sceneform.ArSceneView.onBeginFrame(SourceFile:102)
        at com.google.ar.sceneform.SceneView.doFrameNoRepost(SourceFile:90)
        at com.google.ar.sceneform.SceneView.doFrame(SourceFile:86)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2020-03-04 10:03:47.230 26416-26626/com.skwids E/ACameraMetadata: getConstEntry: cannot find metadata tag 65576
2020-03-04 10:03:47.236 26416-26623/com.skwids W/native: tracking.cc:3753 Feature descriptors not exist
2020-03-04 10:03:47.237 26416-26623/com.skwids W/native: box_detector.cc:180 Detection skipped due to empty features or descriptors.
2020-03-04 10:03:47.269 26416-26626/com.skwids E/ACameraMetadata: getConstEntry: cannot find metadata tag 65576
2020-03-04 10:03:47.272 26416-26622/com.skwids W/native: tracking.cc:3753 Feature descriptors not exist
2020-03-04 10:03:47.272 26416-26622/com.skwids W/native: box_detector.cc:180 Detection skipped due to empty features or descriptors.
2020-03-04 10:03:47.306 26416-26626/com.skwids E/ACameraMetadata: getConstEntry: cannot find metadata tag 65576
2020-03-04 10:03:47.314 26416-26621/com.skwids W/native: tracking.cc:3753 Feature descriptors not exist
2020-03-04 10:03:47.314 26416-26621/com.skwids W/native: box_detector.cc:180 Detection skipped due to empty features or descriptors.
2020-03-04 10:03:47.334 26416-26626/com.skwids E/ACameraMetadata: getConstEntry: cannot find metadata tag 65576
2020-03-04 10:03:47.344 26416-26622/com.skwids W/native: tracking.cc:3753 Feature descriptors not exist
2020-03-04 10:03:47.344 26416-26622/com.skwids W/native: box_detector.cc:180 Detection skipped due to empty features or descriptors.
2020-03-04 10:03:47.394 26416-26626/com.skwids E/ACameraMetadata: getConstEntry: cannot find metadata tag 65576
```

**Comment by JGregoryAtiba** [comment]
I switched my AVD to API 29 x86 (Google APIs) and the crash went away.
