### ISSUE TITLE
Android Studio crashes on installing plugi version 1.15.0

### ISSUE THREAD

**Issue by vipulsinghal23** [google-ar/sceneform-android-sdk#1036]
I am using Android Studio 3.6 and plugin version 1.15.0 (sceneform plugin and all dependencies). 
Android Studio keep crashing after installing this plugin. Please help for me for this. Following is the log :-

Plugin Error: Plugin 'google-sceneform-tools' failed to initialize and will be disabled.  Please restart Android Studio.

java.lang.UnsatisfiedLinkError: C:\Users\vipul.singhal\AppData\Local\Temp\sceneform-filament-jni8557919383381441517\filament-jni.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at com.google.android.filament.Filament.<clinit>(Filament.java:22)
        at com.google.ar.sceneform.plugin.viewer.FilamentProvider.startEngine(FilamentProvider.java:92)
        at com.google.ar.sceneform.plugin.viewer.FilamentProvider.initComponent(FilamentProvider.java:33)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414)
        at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:153)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:438)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by kulnaman** [comment]
Hi in the latest version of sceneform the sceneform plugin is depreciated and for 3d objects gltf/glb format is now used, for detailed overview of the changes, Kindly refer to https://github.com/google-ar/sceneform-android-sdk/releases
