### ISSUE TITLE
Google Sceneform Tools (Beta) plugin crashes Android Studio 3.6

### ISSUE THREAD

**Issue by CelikAbdullah** [google-ar/sceneform-android-sdk#1057]
Hello 

I tried the "Introduction to Sceneform" codelab [here](https://codelabs.developers.google.com/codelabs/sceneform-intro/index.html?index=..%2F..index#0)  but whenever I install the "Google Sceneform Tools (Beta)" plugin and restart the IDE, Android Studio crashes with the following error:

```
Start Failed: Internal error. Please refer to https://code.google.com/p/android/issues

java.lang.IllegalStateException: Couldn't create Engine
	at com.google.android.filament.Engine.create(Engine.java:46)
	at com.google.ar.sceneform.plugin.viewer.Filamentor$3.run(Filamentor.java:103)
```

I also tested older versions of the Google Sceneform Tools (Beta) plugin [from the official website](https://plugins.jetbrains.com/plugin/10698-google-sceneform-tools-beta-) but Android Studio 3.6 still crashes.
I use Android Studio 3.6. Can someone provide a solution for this problem?

**Comment by tellypresence** [comment]
(duplicate of several issues including https://github.com/google-ar/sceneform-android-sdk/issues/989)

Things are in a transitional state right now, the plugin is deprecated but v1.16.0
still has some breakage and incomplete features and documentation (also
not AndroidX ready and no maven dep) so not a drop-in replacement yet; but
no new fixes on the plugin would be expected either.

So you may need to run two versions of Android Studio,
one for converting assets using the plugin and the other (3.6) for main development;
fortunately the .sfb doesn't depend on the plugin once it's converted so you can
just copy to res/raw and everything should work.
