### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method requireActivity()Landroid/support/v4/app/FragmentActivity; in class Lcom/google/ar/sceneform/ux/BaseArFragment; or its super classes (declaration of 'com.google.ar.sceneform.ux.BaseArFragment' appears in /data/app/example-1/split_lib_dependencies_apk.apk:classes2.dex)

### ISSUE THREAD

**Issue by pk4393** [google-ar/sceneform-android-sdk#129]
Hey all,

It looks like sceneform 1.0.0 is crashing with the following stack trace:

at com.google.ar.sceneform.ux.BaseArFragment.initializeSession(BaseArFragment.java:355)
        at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:335)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2308)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1465)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3191)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:214)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:482)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:471)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
        at android.app.Activity.performResume(Activity.java:7082)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2991)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by malik-at-work** [comment]
Is this perhaps a multidex issue?

**Comment by malik-at-work** [comment]
Closing due to inactivity. Reopen if there is more info to add on this.

**Comment by basitsaleemmb** [comment]
@inio @gstanlo
getting the same issue

**Comment by malik-at-work** [comment]
Thanks for the bug report.  More info would help us track this down.
Here are some things that might help us out:

What phone are you on (check settings->system->about phone->model)
What version of android are you running (check settings->system-> about phone->build number)
What version of Arcore & Sceneform do you have installed? (apps->see all apps ... show system >ARCore->App details)
And also if you can grab the log around this error.. There may be another message in the log which would be useful.

Was this working for you previously? When did it stop working?

**Comment by basitsaleemmb** [comment]
@malik-at-work  
phone - Samsung galaxy s7 
android version - 7.0 Api level 24
ar with latest version installed
yep this was working fine previously and crash is [here ](https://github.com/google-ar/sceneform-android-sdk/issues/248)

**Comment by claywilkinson** [comment]
requireActivity() method was added in the 27.1.0 support library.  Please update your application to use 
  "com.android.support:appcompat-v7:27.1.0" or greater.
