### ISSUE TITLE
create many ViewRenderables 

### ISSUE THREAD

**Issue by MohamedElshafey** [google-ar/sceneform-android-sdk#219]
How to force ArSceneView to GC the ViewRenderables?
i make many ViewRenderables and after a while the app crashes due to this error

`java.lang.IllegalArgumentException
        at android.view.Surface.nativeLockCanvas(Native Method)
        at android.view.Surface.lockCanvas(Surface.java:330)
        at com.google.ar.sceneform.rendering.RenderViewToSurfaceTexture.dispatchDraw(RenderViewToSurfaceTexture.java:107)
        at android.view.View.updateDisplayListIfDirty(View.java:19288)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4405)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4385)
        at android.view.View.updateDisplayListIfDirty(View.java:19256)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3447)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3234)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2769)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1738)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7745)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by gstanlo** [comment]
How many ViewRenderables are you using simultaneously?

**Comment by MohamedElshafey** [comment]
I was trying to use more than 120 ViewRenderables at the same time, but i found that i can't so i put a limit to the ViewRenderables  to be max 70 Renderable, and reusing them each time i want new items, so i'm asking if there is a way to force GC to clear them instead of reusing them.

** The app logic is to show some ViewRenderables and clear them to create new ones if the user location changed, each session might contain up to thousand ViewRenderables.

**Comment by dsternfeld7** [comment]
Thanks for the info! Also, what device / android  version you are testing this on? Also, Sceneform 1.4 includes some performance improvements for ViewRenderable's do you see any difference in behavior in Sceneform 1.4?

**Comment by MohamedElshafey** [comment]
@dsternfeld7 tested on two devices, Samsung S8+ 8.0.0 and Nexus 6P 8.1.0, I didn't use Sceneform 1.4 yet, I will test it and feedback you later.
Thanks.

@dakshsrivastava No i'm not using anchors.

**Comment by dsternfeld7** [comment]
Hey MohamedElshafey! How is it going?

So to be clear - you are using ~70 View Renderables at the same time, and want a way to force them to be disposed before the garbage collector runs when you clear some of those view renderables and create new ones so that you don't run out of memory?

**Comment by MohamedElshafey** [comment]
@dsternfeld7 actually with Sceneform 1.4 the performance is better and i can make ~150 ViewRenderables at the same time.
and answering your question, yes that's what i want , to dispose before GC runs.

Thanks.
