### ISSUE TITLE
[Bug] SceneForm application throws error on Pixel 2 Emulator even with OpenGL ES 3.0

### ISSUE THREAD

**Issue by dakshsrivastava** [google-ar/sceneform-android-sdk#231]
Kudos on making SceneForm work with Emulators on Mac with openGL ES 3.0. I've been waiting for this for sometime. 

However, it doesn't work. I repeatedly get the error message "E/StandardArFragment: Error: Failed to create AR session" while working with the following device profile : 
1. Pixel 2 XL
2. API 27 x86 Google API image 
3. The ADB command reports my Macbook pro has OpenGL ES 3.0
4.  Backcamera with Emulated scene. (Camera app works fine. I'm able to roam around the cat and the dog)

The following excerpt from the stacktrace caught my attention : 
```
I/native: android_camera.cc:1117 Initializing camera manager.
I/native: android_camera.cc:1133 Camera manager initialized successfully with 1 cameras.
E/native: status.cc:155 generic::internal: Physical cameras don't match device profile. Camera not found. camera_id=1, cameras count=1
    session_create_implementation.cc:169 Failed to initilize the data source - -2
    session_create_implementation.cc:170 ArSession_createImplementation returning ArStatusErrorSpace::AR_ERROR_FATAL: .
```

**Comment by dakshsrivastava** [comment]
* sigh * Okay, I got it working. 
This was the clue : `Physical cameras don't match device profile. Camera not found. camera_id=1, cameras count=1`. 

The emulator needs to be setup with both cameras. I only configured the back camera and not the front.

**Comment by jwmcglynn** [comment]
Thanks for calling that our @dakshsrivastava.  Yeah, I have an ARCore bug filed on that which didn't make it into the 1.4 release.  For now, the emulator must be configured with both a front and back camera.

If anyone else runs into that issue, double check that your front camera is `emulated` and the back camera is `virtualscene`.

**Comment by VadlamudiNaveen** [comment]
can anyone please solve this problem ...
please i am getting : i am getting AR session failed to create

E/native: status.cc:156 generic::internal: Physical cameras don't match device profile. 1 expected back facing:CameraDirection::kFrontFacing actual back facing:CameraDirection::kRearFacing
    session_create_implementation_shared.cc:1466 Failed to initilize the data source - -2
E/native: session_create_implementation_shared.cc:1467 CreateLiveSessionWithMostDependencies returning ArStatusErrorSpace::AR_ERROR_FATAL: .
I/native: feature_combo_node.cc:175 Cleared scoped_image buffers in feature_combo.
I/native: android_camera.cc:713 Reset cleanly got to CLOSED state for camera 1
I/native: android_camera.cc:713 Reset cleanly got to CLOSED state for camera 0
I/native: session_create_implementation.cc:147 ArSession_createWithSettingsImplementation_private returning ArStatusErrorSpace::AR_ERROR_FATAL: .
V/third_party/redwood/base/jni_common/jni_helper.cc: ~JniHelper: about to detach thread (Called from line 189).
    ~JniHelper: detached thread (Called from line 189).
E/StandardArFragment: Error: Failed to create AR session
    com.google.ar.core.exceptions.UnavailableException
        at com.google.ar.sceneform.ux.BaseArFragment.initializeSession(BaseArFragment.java:356)
        at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:311)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
        at android.app.Activity.performResume(Activity.java:7141)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: com.google.ar.core.exceptions.FatalException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:143)
        at com.google.ar.core.Session.nativeCreateSessionWithFeatures(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:23)
        at com.google.ar.sceneform.ux.BaseArFragment.createSessionWithFeatures(BaseArFragment.java:381)
        at com.google.ar.sceneform.ux.BaseArFragment.createSession(BaseArFragment.java:370)
        at com.google.ar.sceneform.ux.BaseArFragment.initializeSession(BaseArFragment.java:344)
        at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:311) 
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269) 
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241) 
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223) 
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538) 
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527) 
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172) 
        at android.app.Activity.performResume(Activity.java:7141) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by AndroidLibrariesYoutube** [comment]
I am also getting the same problem. 
[https://stackoverflow.com/questions/55981054/failed-to-create-ar-session-android-sceneform](url)

I think the issue is with the android emulator. The emulator is unable to create the Virtual Scene.
