### ISSUE TITLE
Glb supported but not properly working?

### ISSUE THREAD

**Issue by Meenners** [google-ar/sceneform-android-sdk#346]
Hi yall,
Running into a little bit of an issue with the new update (GLTF/GLB).  I know this was just added so I wanted to share this for future reference or, if im doing something wrong please let me know :)  The GLTF2 version works great!  However, when I tried GLB, i get unable to load Renderable issues, regardless who made the GLB.  Am i missing something?  

```java
private void GenerateRenderable(String model) {
model = "https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Duck/glTF-Binary/Duck.glb";

        ModelRenderable.builder()
                .setSource(this, RenderableSource.builder().setSource(
                        this,
                        Uri.parse(model),
                        RenderableSource.SourceType.GLB).build())
                .setRegistryId(Uri.parse(model))
                .build()
                .thenAccept(renderable -> {
                    modelRenderable = renderable;
                })
                .exceptionally (
                        throwable -> {
                            Toast toast = Toast.makeText(this, "Unable to load model renderable", Toast.LENGTH_LONG);
                            toast.setGravity(Gravity.CENTER, 0, 0);
                            toast.show();
                            return null;
                        });
}
```

```ModelRenderable: Unable to load Renderable registryId='https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Duck/glTF-Binary/Duck.glb'
    java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to import '/data/user/0/com.google.ar.sceneform.samples.hellosceneform/cache/1538500594339-0/model_source.glb'
        at com.google.ar.sceneform.rendering.LoadRenderableFromSfbTask.inputStreamToByteBuffer(LoadRenderableFromSfbTask.java:189)
        at com.google.ar.sceneform.rendering.LoadRenderableFromSfbTask.lambda$downloadAndProcessRenderable$0(LoadRenderableFromSfbTask.java:121)
        at com.google.ar.sceneform.rendering.-$$Lambda$LoadRenderableFromSfbTask$0DkaOpfpmr8DYlbaxWogZtUpKTw.get(Unknown Source:4)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1625)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: Failed to import '/data/user/0/com.google.ar.sceneform.samples.hellosceneform/cache/1538500594339-0/model_source.glb'
```

**Comment by gstanlo** [comment]
The URL you linked to is incorrect; it is the github page for it, and you need the raw file instead. When Sceneform loads it, it's reading a bunch of HTML and not the glb file. 

Instead of:
[https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Duck/glTF-Binary/Duck.glb](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Duck/glTF-Binary/Duck.glb)

use this instead:
[https://github.com/KhronosGroup/glTF-Sample-Models/**raw**/master/2.0/Duck/glTF-Binary/Duck.glb](https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/Duck/glTF-Binary/Duck.glb)

**Comment by Meenners** [comment]
well.... i feel dumb lol   thank you!
