### ISSUE TITLE
Application slows down and hangs

### ISSUE THREAD

**Issue by aswini149** [google-ar/sceneform-android-sdk#40]
i have changed the demo code a little, but 3d models are not rendered. When i debug it crashes at createAnchor().

When application resumes i am trying to call like this...
arSceneView
              .getScene()
              .setOnUpdateListener(
                      frameTime -> {
                          Frame frame = arSceneView.getArFrame();
                          if (frame == null) {
                              return;
                          }

                          if (frame.getCamera().getTrackingState() != TrackingState.TRACKING) {
                              return;
                          }
                          if(frame != null && !hasPlacedSolarSystem) {
                              hasPlacedSolarSystem = tryPlaceSolarSystem(null, frame);
                          }
                      });

Also the applications slows down and hangs.

**Comment by aswini149** [comment]
i am on Pixel, and along with i am getting all sensor data & location. Will this impact the performance of app ?

**Comment by claywilkinson** [comment]
@aswini149 - it is possible.  Can you share a log of when it starts to hang?

**Comment by aswini149** [comment]
05-24 10:10:04.928 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:04.928 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem expire 6 lines
05-24 10:10:04.928 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:04.944 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.008 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 6 lines
05-24 10:10:05.009 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.034 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.209 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 16 lines
05-24 10:10:05.209 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.223 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.291 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 5 lines
05-24 10:10:05.293 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.310 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.311 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 1 line
05-24 10:10:05.323 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.330 21712-21723/com.google.ar.sceneform.samples.solarsystem I/zygote64: Background concurrent copying GC freed 7347(441KB) AllocSpace objects, 61(100MB) LOS objects, 48% free, 25MB/49MB, paused 269us total 677.225ms
05-24 10:10:05.345 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
    hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.351 21712-21749/com.google.ar.sceneform.samples.solarsystem W/native: data_synchro.cc:70 Can not add image for camera 0: image-valid status is 1 and image-expiry status is 1.
05-24 10:10:05.370 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.475 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 11 lines
05-24 10:10:05.490 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.506 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.625 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 10 lines
05-24 10:10:05.625 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.642 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.642 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 1 line
05-24 10:10:05.656 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:05.909 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:06.001 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:06.107 21712-21712/com.google.ar.sceneform.samples.solarsystem V/StudioProfiler: StudioProfilers agent attached.
05-24 10:10:06.238 21712-21942/com.google.ar.sceneform.samples.solarsystem V/StudioProfiler: Acquiring Application for Events
05-24 10:10:06.289 21712-21712/com.google.ar.sceneform.samples.solarsystem V/StudioProfiler: Transformed class: java/net/URL
05-24 10:10:06.592 21712-21717/com.google.ar.sceneform.samples.solarsystem I/zygote64: Do full code cache collection, code=107KB, data=108KB
    After code cache collection, code=105KB, data=86KB
05-24 10:10:06.611 21712-21712/com.google.ar.sceneform.samples.solarsystem W/zygote64: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
05-24 10:10:06.697 21712-21712/com.google.ar.sceneform.samples.solarsystem V/StudioProfiler: Memory control stream started.
05-24 10:10:06.709 21712-21712/com.google.ar.sceneform.samples.solarsystem I/Choreographer: Skipped 42 frames!  The application may be doing too much work on its main thread.
05-24 10:10:06.719 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:06.752 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:07.048 21712-21717/com.google.ar.sceneform.samples.solarsystem I/zygote64: Do partial code cache collection, code=124KB, data=93KB
05-24 10:10:07.049 21712-21717/com.google.ar.sceneform.samples.solarsystem I/zygote64: After code cache collection, code=120KB, data=91KB
    Increasing code cache capacity to 512KB
05-24 10:10:07.242 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:07.979 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 30 lines
05-24 10:10:07.993 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:07.996 21712-21948/com.google.ar.sceneform.samples.solarsystem V/StudioProfiler: Live memory tracking disabled.
05-24 10:10:08.000 21712-21948/com.google.ar.sceneform.samples.solarsystem V/StudioProfiler: Live memory tracking enabled.
    JNIEnv not attached
05-24 10:10:08.010 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:08.060 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 3 lines
05-24 10:10:08.079 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:08.089 21712-21948/com.google.ar.sceneform.samples.solarsystem V/StudioProfiler: Loaded classes: 5552
05-24 10:10:08.093 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:08.169 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 4 lines
05-24 10:10:08.184 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:08.222 21712-21749/com.google.ar.sceneform.samples.solarsystem W/native: data_synchro.cc:70 Can not add image for camera 0: image-valid status is 1 and image-expiry status is 1.
05-24 10:10:08.826 21712-21948/com.google.ar.sceneform.samples.solarsystem V/StudioProfiler: Tracking initialization took: 826246280ns
05-24 10:10:08.891 21712-21712/com.google.ar.sceneform.samples.solarsystem I/Choreographer: Skipped 41 frames!  The application may be doing too much work on its main thread.
05-24 10:10:08.993 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:09.023 21712-21748/com.google.ar.sceneform.samples.solarsystem W/native: data_synchro.cc:70 Can not add image for camera 0: image-valid status is 1 and image-expiry status is 1.
05-24 10:10:09.050 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:09.165 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:09.287 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:09.622 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 4 lines
05-24 10:10:09.674 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:09.742 21712-21749/com.google.ar.sceneform.samples.solarsystem W/native: data_synchro.cc:70 Can not add image for camera 0: image-valid status is 1 and image-expiry status is 1.
05-24 10:10:09.806 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:10.114 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 4 lines
05-24 10:10:10.155 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:10.284 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:10.629 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 4 lines
05-24 10:10:10.680 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:10.737 21712-21743/com.google.ar.sceneform.samples.solarsystem I/native: performance_monitor.cc:121 Event: FeatureExtraction is taking too long, it took 136.42ms
05-24 10:10:10.897 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:11.033 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 1 line
05-24 10:10:11.076 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:11.186 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:11.293 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:11.333 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:11.430 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:11.627 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 2 lines
05-24 10:10:11.675 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:11.766 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:11.806 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:11.899 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:11.950 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 1 line
05-24 10:10:12.053 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:12.093 21712-21749/com.google.ar.sceneform.samples.solarsystem I/native: visual_inertial_wls.cc:775 ShouldSplitMap time: 0.00772339
05-24 10:10:12.103 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:12.163 21712-21743/com.google.ar.sceneform.samples.solarsystem I/native: performance_monitor.cc:121 Event: FeatureExtraction is taking too long, it took 130.734ms
05-24 10:10:12.200 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:12.247 21712-21749/com.google.ar.sceneform.samples.solarsystem I/native: viwls_optimization.cc:1226 Skip Lite-COM due to a significant calibration change.
05-24 10:10:12.248 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:12.349 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:12.393 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:12.433 21712-21748/com.google.ar.sceneform.samples.solarsystem W/native: data_synchro.cc:70 Can not add image for camera 0: image-valid status is 1 and image-expiry status is 1.
05-24 10:10:12.487 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:12.526 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:12.590 21712-21749/com.google.ar.sceneform.samples.solarsystem I/native: viwls_optimization.cc:1066 MAP SOLVE: USER_SUCCESS
05-24 10:10:12.594 21712-21749/com.google.ar.sceneform.samples.solarsystem I/native: visual_inertial_wls.cc:468 online_viwls_solve_time in seconds = 0.500768 solve_time_counter_ = 0
    multi_map_manager.cc:446 Added ADF into multi_map_manager: 36707efb-3b86-24d0-9488-a97ad48f6b1a
05-24 10:10:12.595 21712-21747/com.google.ar.sceneform.samples.solarsystem W/native: data_synchro.cc:70 Can not add image for camera 0: image-valid status is 1 and image-expiry status is 1.
05-24 10:10:12.595 21712-21747/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) tango_lp_0 identical 1 line
05-24 10:10:12.596 21712-21747/com.google.ar.sceneform.samples.solarsystem W/native: data_synchro.cc:70 Can not add image for camera 0: image-valid status is 1 and image-expiry status is 1.
05-24 10:10:12.620 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:12.647 21712-21748/com.google.ar.sceneform.samples.solarsystem W/native: data_synchro.cc:70 Can not add image for camera 0: image-valid status is 1 and image-expiry status is 1.
05-24 10:10:12.670 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:12.782 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 1 line
05-24 10:10:12.830 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:12.926 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:13.066 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 2 lines
05-24 10:10:13.155 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:13.200 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:13.290 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:13.336 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:13.431 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:13.570 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:13.595 21712-21717/com.google.ar.sceneform.samples.solarsystem I/zygote64: Compiler allocated 6MB to compile void android.view.ViewRootImpl.performTraversals()
05-24 10:10:13.624 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:13.858 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 3 lines
05-24 10:10:13.899 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:14.429 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:14.698 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 4 lines
05-24 10:10:14.746 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:14.908 21712-21746/com.google.ar.sceneform.samples.solarsystem I/native: log_per_line.cc:19 SM Timing
    log_per_line.cc:19 -----------
    log_per_line.cc:19  VIWLS 1.1: Check whether to split large maps and compute the transformation from VIO.	      1	 0.007723	( 0.007723 +-  0.000000)	[ 0.007723, 0.007723]
    log_per_line.cc:19 Statistics
    log_per_line.cc:19 -----------                      #	Hz	(avg     +- std    )	[min,max]
    log_per_line.cc:19 VIO_filter_reset            	      1	282406	(1 +- 0)	[1,1]
    log_per_line.cc:19 VIWLS_num_map_solves_success	      1	2349.49	(1 +- 0)	[1,1]
    log_per_line.cc:19 VIWLS_solve_time            	      1	176149	(0.500768 +- 0)	[0.500768,0.500768]
05-24 10:10:14.953 21712-21717/com.google.ar.sceneform.samples.solarsystem I/zygote64: Do full code cache collection, code=250KB, data=172KB
05-24 10:10:14.968 21712-21717/com.google.ar.sceneform.samples.solarsystem I/zygote64: After code cache collection, code=197KB, data=120KB
05-24 10:10:15.137 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:15.177 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:15.432 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:15.772 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 4 lines
05-24 10:10:15.815 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:15.901 21712-21743/com.google.ar.sceneform.samples.solarsystem I/native: performance_monitor.cc:121 Event: FeatureExtraction is taking too long, it took 112.138ms
05-24 10:10:15.906 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:16.033 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 2 lines
05-24 10:10:16.070 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:16.309 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:16.685 21712-21712/com.google.ar.sceneform.samples.solarsystem I/chatty: uid=10309(u0_a309) com.google.ar.sceneform.samples.solarsystem identical 6 lines
05-24 10:10:16.783 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:16.821 21712-21745/com.google.ar.sceneform.samples.solarsystem E/native: filter_update_base.cc:83 Temporary visual feature update failed when computing its residual and Jacobian.
05-24 10:10:16.821 21712-21745/com.google.ar.sceneform.samples.solarsystem I/native: vio_fault_detector.cc:489 VIO did not use vision constraints.
05-24 10:10:16.828 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:16.914 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:16.924 21712-21745/com.google.ar.sceneform.samples.solarsystem E/native: filter_update_base.cc:83 Temporary visual feature update failed when computing its residual and Jacobian.
05-24 10:10:16.924 21712-21745/com.google.ar.sceneform.samples.solarsystem I/native: vio_fault_detector.cc:489 VIO did not use vision constraints.
05-24 10:10:16.949 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:17.035 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:17.035 21712-21745/com.google.ar.sceneform.samples.solarsystem E/native: filter_update_base.cc:83 Temporary visual feature update failed when computing its residual and Jacobian.
05-24 10:10:17.035 21712-21745/com.google.ar.sceneform.samples.solarsystem I/native: vio_fault_detector.cc:489 VIO did not use vision constraints.
05-24 10:10:17.071 21712-21712/com.google.ar.sceneform.samples.solarsystem E/native: hit_test.cc:358 generic::internal: No point hit.
05-24 10:10:17.297 21712-21745/com.google.ar.sceneform.samples.solarsystem E/native: filter_update_base.cc:83 Temporary visual feature update failed when computing its residual and Jacobian.
05-24 10:10:17.298 21712-21745/com.google.ar.sceneform.samples.solarsystem I/native: vio_fault_detector.cc:489 VIO did not use vision constraints.
05-24 10:10:17.370 21712-21746/com.google.ar.sceneform.samples.solarsystem E/native: filter_update_base.cc:83 Temporary visual feature update failed when computing its residual and Jacobian.
05-24 10:10:17.370 21712-21746/com.google.ar.sceneform.samples.solarsystem I/native: vio_fault_detector.cc:489 VIO did not use vision constraints.
05-24 10:10:17.539 21712-21746/com.google.ar.sceneform.samples.solarsystem E/native: filter_update_base.cc:83 Temporary visual feature update failed when computing its residual and Jacobian.
05-24 10:10:17.539 21712-21746/com.google.ar.sceneform.samples.solarsystem W/native: vio_fault_detector.cc:338 Fault: Lack of valid visual measurements.

**Comment by dsternfeld7** [comment]
In your project, did you reconfigure the AR Core Session? If so, it may be slowing down if the update mode isn't sent to LATEST_CAMERA_IMAGE, which is [required](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/ArSceneView.html#setupSession(com.google.ar.core.Session)) for Sceneform.

`config.setUpdateMode(Config.UpdateMode.LATEST_CAMERA_IMAGE);`

For the crash, can you please post a log that includes the stack trace of the crash?

Thanks,

Dan

**Comment by aswini149** [comment]
while debugging, i put a debug point at  Anchor anchor = hit.createAnchor();

--------- beginning of crash
05-30 13:29:48.841 18176-18176/com.google.ar.sceneform.samples.solarsystem E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.ar.sceneform.samples.solarsystem, PID: 18176
    com.google.ar.core.exceptions.FatalException
        at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:43)
        at com.google.ar.core.HitResult.nativeCreateAnchor(Native Method)
        at com.google.ar.core.HitResult.createAnchor(Unknown Source:6)
        at com.google.ar.sceneform.samples.solarsystem.SolarActivity.tryPlaceSolarSystem(SolarActivity.java:438)
        at com.google.ar.sceneform.samples.solarsystem.SolarActivity.lambda$onResume$2$SolarActivity(SolarActivity.java:289)
        at com.google.ar.sceneform.samples.solarsystem.SolarActivity$$Lambda$2.onUpdate(Unknown Source:2)
        at com.google.ar.sceneform.Scene.dispatchUpdate(Unknown Source:6)
        at com.google.ar.sceneform.SceneView.doFrame(Unknown Source:36)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

bdw is there any other way of creating a anchor except from a hit ?

**Comment by dsternfeld7** [comment]
@aswini149 Following up on this, has there been any developments or are you still encountering the same issue? I haven't been able to reproduce it internally yet. what device are you testing on? What version of ArCore and Sceneform?

Also, you can create an anchor directly by using Session.createAnchor or Trackable.createAnchor.

**Comment by dsternfeld7** [comment]
Closing due to inactivity.
