### ISSUE TITLE
API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()

### ISSUE THREAD

**Issue by dmitry-kanunnikoff** [google-ar/sceneform-android-sdk#408]
Good afternoon. 

Thank you very much for your work. 

But I have a problem with the latest plugin version (1.5.0) - Android Studio "says", that "API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'. It will be removed at the end of 2019.". 
And seems the problem is in your plugin. It is the stacktrace: 

> To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace. at com.android.builder.errors.EvalIssueReporter$DefaultImpls.reportIssue(EvalIssueReporter.kt:94) at com.android.build.gradle.internal.errors.SyncIssueHandler$DefaultImpls.reportIssue(SyncIssueHandler.kt) at com.android.build.gradle.internal.errors.SyncIssueHandlerImpl.reportIssue(SyncIssueHandlerImpl.kt:31) at com.android.builder.errors.EvalIssueReporter$DefaultImpls.reportIssue(EvalIssueReporter.kt:117) at com.android.build.gradle.internal.errors.SyncIssueHandler$DefaultImpls.reportIssue(SyncIssueHandler.kt) at com.android.build.gradle.internal.errors.SyncIssueHandlerImpl.reportIssue(SyncIssueHandlerImpl.kt:31) at com.android.build.gradle.internal.errors.DeprecationReporterImpl.reportDeprecatedApi(DeprecationReporterImpl.kt:77) at com.android.build.gradle.internal.api.BaseVariantImpl.getMergeResources(BaseVariantImpl.java:333) at com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated.getMergeResources(Unknown Source) at com.google.ar.sceneform.plugin.SceneformAssets$1.execute(SceneformAssets.java:54) at com.google.ar.sceneform.plugin.SceneformAssets$1.execute(SceneformAssets.java:47) at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1$1.run(DefaultListenerBuildOperationDecorator.java:155) at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:58) at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152) at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300) at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292) at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174) at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90) at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction.execute(DefaultListenerBuildOperationDecorator.java:149) at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91) at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80) at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42) at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230) at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149) at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58) at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324) at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234) at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140) at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37) at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93) at com.sun.proxy.$Proxy33.afterEvaluate(Unknown Source) at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:187) at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:184) at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1418) at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:193) at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300) at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292) at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174) at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90) at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31) at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:110) at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300) at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292) at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174) at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90) at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31) at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:68) at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:687) at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:140) at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35) at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62) at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41) at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:274) at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300) at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292) at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174) at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90) at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31) at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:182) at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:141) at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124) at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77) at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74) at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154) at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38) at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96) at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74) at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:55) at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35) at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35) at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32) at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:50) at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300) at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292) at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174) at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90) at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31) at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45) at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51) at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47) at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44) at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79) at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44) at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30) at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39) at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25) at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80) at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53) at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62) at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34) at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36) at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25) at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43) at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29) at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59) at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31) at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59) at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44) at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46) at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30) at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67) at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122) at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37) at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122) at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26) at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122) at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34) at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122) at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74) at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72) at org.gradle.util.Swapper.swap(Swapper.java:38) at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72) at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122) at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55) at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122) at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62) at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122) at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81) at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36) at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122) at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50) at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295) at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) at java.lang.Thread.run(Thread.java:745) 

And it is the reason, why I can't to connect to Firebase and to configure the notifications in my app. 
Please, fix the problem in the future release. 
Thank you in advance. 
Regards.

**Comment by somoreingold** [comment]
Perhaps this is related:

`WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: It is currently called from the following trace:
java.lang.Thread.getStackTrace(Thread.java:1556)
com.android.build.gradle.internal.errors.DeprecationReporterImpl.reportDeprecatedApi(DeprecationReporterImpl.kt:79)
com.android.build.gradle.internal.api.BaseVariantImpl.getMergeAssets(BaseVariantImpl.java:374)
com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated.getMergeAssets(null:-1)
com.google.ar.sceneform.plugin.SceneformAssets$1.execute(SceneformAssets.java:55)
com.google.ar.sceneform.plugin.SceneformAssets$1.execute(SceneformAssets.java:47)
...`

**Comment by kenchoong** [comment]
Bro do you solve this problem??I also face this

**Comment by kenchoong** [comment]
`implementation 'com.google.ar.sceneform.ux:sceneform-ux:1.7.0'`

Gradle version : gradle-4.10.1-all.zip
Android studio version : 3.3.1

I got this log when build the project 

> WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
> It will be removed at the end of 2019.

the details log is same with @somoreingold at the top

**Comment by dmitry-kanunnikoff** [comment]
> Bro do you solve this problem??I also face this

The problem is still here.
But you can switch off this plugin, sync and try to connect to Firebase again - must be success now.

After successful connection to Firebase you can return your plugin and resync. Warning will appear again, but it is not important, because Firebase has configured already.

**Comment by KrishnaEpam** [comment]
> `implementation 'com.google.ar.sceneform.ux:sceneform-ux:1.7.0'`
> 
> Gradle version : gradle-4.10.1-all.zip
> Android studio version : 3.3.1
> 
> I got this log when build the project
> 
> > WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
> > It will be removed at the end of 2019.
> 
> the details log is same with @dmitry-kanunnikoff at the top

Thank you, after changed version working fine

**Comment by Sogrey** [comment]
I also face this,too.And found the version `1.5.1` working fine.

project gradle:
``` gradle
buildscript {
    
    repositories {
        google()
        ...
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.ar.sceneform:plugin:1.5.1'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```
app gradle:
``` gradle

dependencies {
    ...
    implementation "com.google.ar.sceneform.ux:sceneform-ux:1.5.1"

}

apply plugin: 'com.google.ar.sceneform.plugin'
sceneform.asset('sampledata/tiger/Mesh_BengalTiger.obj',
        'default',
        'sampledata/tiger/Mesh_BengalTiger.sfa',
        'src/main/assets/Mesh_BengalTiger')
```

**Comment by calmmycode** [comment]
Same here.

**Comment by Moritz-David** [comment]
The plugin developers need to apply the pull request for the solution of the problem.
As you can see here: [https://github.com/google/play-services-plugins/pull/62](url)

**Comment by numankaraaslan** [comment]
In my case, it was caused from gms services 4.3.0. So i had to change it to:

`com.google.gms:google-services:4.2.0`

I have found this by running:

`gradlew sync -Pandroid.debug.obsoleteApi=true`

in terminal. Go to view -> tool windows -> Terminal in Android Studio.
Gms services will probably fix this in the future versions.

**Comment by obedi123** [comment]
> In my case, it was caused from gms services 4.3.0. So i had to change it to:
> 
> `com.google.gms:google-services:4.2.0`
> 
> I have found this by running:
> 
> `gradlew sync -Pandroid.debug.obsoleteApi=true`
> 
> in terminal. Go to view -> tool windows -> Terminal in Android Studio.
> Gms services will probably fix this in the future versions.

Thanks bro, this worked for me.

**Comment by mtrezza** [comment]
I think it's safe to use 4.3. This is a usual warning message that you'll see when upgrading google-services. That warning usually disappears before the method is removed end of 2019.

**Comment by vkotovv** [comment]
@numankaraaslan There is an [issue](https://issuetracker.google.com/issues/136283996) in Google bug tracker devoted to this.

**Comment by vkotovv** [comment]
@numankaraaslan See https://github.com/google/play-services-plugins/issues/65

**Comment by mjjabarullah** [comment]
> In my case, it was caused from gms services 4.3.0. So i had to change it to:
> 
> `com.google.gms:google-services:4.2.0`
> 
> I have found this by running:
> 
> `gradlew sync -Pandroid.debug.obsoleteApi=true`
> 
> in terminal. Go to view -> tool windows -> Terminal in Android Studio.
> Gms services will probably fix this in the future versions.

worked..... wow..

**Comment by amitabha2715** [comment]
Still now...

````
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app

````

**Comment by mjjabarullah** [comment]
Chane com.google.gms:google-services:4.2.0 clastpath in project level gradle.

**Comment by Gunjan9sahoo** [comment]
Failed to resolve: com.android.support.appcompat-v7:28.0.0: |  
-- | --
Sync Failed | 8 s 69 ms

ERROR: Failed to resolve: com.android.support.appcompat-v7:28.0.0:
Affected Modules: app
 
how to resolve???

**Comment by mjjabarullah** [comment]
Could you please send screenshot

**Comment by megamendhie** [comment]
I had this warning after updating my classpath to 'com.google.gms:google-services:4.3.0'
So I returned it to 'com.google.gms:google-services:4.1.0' and the warning was gone.

**Comment by numankaraaslan** [comment]
@Gunjan9sahoo maybe you should migrate to android X framework for support libraries.

[Migrate to androidx libraries](https://developer.android.com/jetpack/androidx/migrate)

**Comment by Franzhitze** [comment]
AndroidX does not change the problem. It still exists.

**Comment by Gunjan9sahoo** [comment]
i solved it  thank you very much

**Comment by Gunjan9sahoo** [comment]
i solved it thank you very much

**Comment by harshbarnwal** [comment]
> In my case, it was caused from gms services 4.3.0. So i had to change it to:
> 
> `com.google.gms:google-services:4.2.0`
> 
> I have found this by running:
> 
> `gradlew sync -Pandroid.debug.obsoleteApi=true`
> 
> in terminal. Go to view -> tool windows -> Terminal in Android Studio.
> Gms services will probably fix this in the future versions.

worked 👍

**Comment by shahzadafridi** [comment]
In my case, it was caused from gms services 4.3.0. So i had to change it to:

com.google.gms:google-services:4.2.0

Thanks man for the answer. It worked for me.

**Comment by meshack34** [comment]
I got this when I run :
_### lorraine@chepkemoi:~/AndroidStudioProjects/MyApplication$ gradlew sync -Pandroid.debug.obsoleteApi=true

Command 'gradlew' not found, did you mean:

  command 'gradle' from deb gradle

Try: sudo apt install <deb name>_

**Comment by GuilhE** [comment]
> I got this when I run :
> _### lorraine@chepkemoi:~/AndroidStudioProjects/MyApplication$ gradlew sync -Pandroid.debug.obsoleteApi=true
> 
> Command 'gradlew' not found, did you mean:
> 
> command 'gradle' from deb gradle
> 
> Try: sudo apt install _

Run like `./gradlew ...`

**Comment by arunkrish1120** [comment]
> Chane com.google.gms:google-services:4.2.0 clastpath in project level gradle.

when i change version 4.2.0 , i got an Exception "com.google.android.gms.common.api.ApiException: 12500:" like this on google signin

**Comment by GitHubEdA** [comment]
> > Chane com.google.gms:google-services:4.2.0 clastpath in project level gradle.
> 
> when i change version 4.2.0 , i got an Exception "com.google.android.gms.common.api.ApiException: 12500:" like this on google signin

I have the same problem. I don't find how to solve it.

**Comment by Deval99** [comment]
> I had this warning after updating my classpath to 'com.google.gms:google-services:4.3.0'

Thanks, it worked

**Comment by karthik030** [comment]
> In my case, it was caused from gms services 4.3.0. So i had to change it to:
> 
> `com.google.gms:google-services:4.2.0`
> 
> I have found this by running:
> 
> `gradlew sync -Pandroid.debug.obsoleteApi=true`
> 
> in terminal. Go to view -> tool windows -> Terminal in Android Studio.
> Gms services will probably fix this in the future versions.

its working.... Thank You

**Comment by essar-qrs** [comment]
Maintain project gradle with these versions
classpath 'com.android.tools.build:gradle:3.4.2'
 classpath 'com.google.gms:google-services:4.2.0'

**Comment by forfireonly** [comment]
classpath 'com.google.gms:google-services:4.2.0' works!

**Comment by Philaris7** [comment]
> In my case, it was caused from gms services 4.3.0. So i had to change it to:
> 
> `com.google.gms:google-services:4.2.0`
> 
> I have found this by running:
> 
> `gradlew sync -Pandroid.debug.obsoleteApi=true`
> 
> in terminal. Go to view -> tool windows -> Terminal in Android Studio.
> Gms services will probably fix this in the future versions.

Worked for me. thanks

**Comment by eldes** [comment]
> In my case, it was caused from gms services 4.3.0. So i had to change it to:
> 
> `com.google.gms:google-services:4.2.0`
> 
> I have found this by running:
> 
> `gradlew sync -Pandroid.debug.obsoleteApi=true`
> 
> in terminal. Go to view -> tool windows -> Terminal in Android Studio.
> Gms services will probably fix this in the future versions.

This works for me.

**Comment by BoD** [comment]
Related issue: https://github.com/google/play-services-plugins/issues/79

**Comment by roshsoftco** [comment]
> In my case, it was caused from gms services 4.3.0. So i had to change it to:
> 
> `com.google.gms:google-services:4.2.0`
> 
> I have found this by running:
> 
> `gradlew sync -Pandroid.debug.obsoleteApi=true`
> 
> in terminal. Go to view -> tool windows -> Terminal in Android Studio.
> Gms services will probably fix this in the future versions.

Both `4.3.0` and `4.3.1` are causing this. I'm surprised to see how Google have not corrected this in the latest version (`4.3.1`).

**Comment by idurvesh** [comment]
I tried to lower the version to 4.2.0, but I still get the same error

**Comment by meshack34** [comment]
would like to make my login button have image how to I go

**Comment by BasilRawashdeh** [comment]
Solved to me by,
1) Go to the (project-level) build.Gradle file;
2) Replace classpath 'com.google.gms:google-services:4.3.0' with an older version like 4.2.0 instead of 4.3.1
good luck,

**Comment by hgoebl** [comment]
With `com.google.gms:google-services:4.3.2` I still have the same warning.
But reverting to 4.2.0 might be worse than having this warning, IMO.

**Comment by C5FR7Q** [comment]
That problem was solved for me with `com.google.gms:google-services:4.3.2`

**Comment by John-Konordo** [comment]
That problem was solved for me with com.google.gms:google-services:4.3.2

**Comment by TokenAtKenz** [comment]
Problem solved for me with com.google.gms:google-services:4,.3.2 as well.

**Comment by 4shadowr** [comment]
Fixed on `com.google.gms:google-services:4.3.3`

**Comment by AmrIsmaiel** [comment]
This should be fixed on  `com.google.gms:google-services:4.3.3`. Reverting to `com.google.gms:google-services:4.2.0` isn't a good solution
