### ISSUE TITLE
Android Studio not opening after installing the plugin 

### ISSUE THREAD

**Issue by mukherjeepritam** [google-ar/sceneform-android-sdk#409]
Error Message "Couldn't create Engine"
Couldn't create Engine
java.lang.IllegalStateException: Couldn't create Engine
	at com.google.android.filament.Engine.create(Engine.java:37)
	at com.google.ar.sceneform.filament.wrapper.Engine.create(Engine.java:14)
	at com.google.ar.sceneform.plugin.viewer.Filament$3.run(Filament.java:192)

**Comment by MohamedMAbdElhafiz** [comment]
To get your IDE back and running you have to remove the plugin from this directory "/.AndroidStudio3.2/config/plugins".

**Comment by HEMAL-VES** [comment]
Hi,

I am using android studio version 3.1.4. When I am updating Google SceneForm Tools(Beta) plugin from 1.4.0 to 1.5.0, android studio stop working in Windows. I have also try to update Android Studio with the latest version (3.2.0 / 3.2.1) but the same issue occurred android studio stop working.

My PC Configuration is as below:
OS: Windows 10 Pro (64 bit)
RAM: 6GB
Processor: Intel Core i3 - 3210 CPU (3.20 GHz)

Android Studio: 3.1.4
Google SceneForm Tool: 1.4.0

Please help me to resolve this issue.

**Comment by maraj91** [comment]
Hi,
I am using the android studio version 3.2.1. When i am installing the <b>google sceneform tools (beta)</b> from plugin after restarting.Android Studio getting crashed. Please suggest some solution for that.

- Android Studio 3.2.1
- Build #AI-181.5540.7.32.5056338, built on October 9, 2018
- JRE: 1.8.0_152-release-1136-b06 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- Windows 7 6.1

**Comment by HEMAL-VES** [comment]
> Hi,
> I am using the android studio version 3.2.1. When i am installing the google sceneform tools (beta) from plugin after restarting.Android Studio getting crashed. Please suggest some solution for that.
> 
> * Android Studio 3.2.1
> * Build #AI-181.5540.7.32.5056338, built on October 9, 2018
> * JRE: 1.8.0_152-release-1136-b06 amd64
> * JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> * Windows 7 6.1

Hi @maraj91 

Follow below steps to resolve your issue.

Step - 1: Remove your **google scene tools (beta)** plugin by going to below path in your PC
C:\Users\***\.AndroidStudio3.2\config\plugins.
And delete google scene form tools folder from your above path

Step - 2: Download Google Scene Form Tools Plugin **version 1.4.0** from below link:

[Google Sceneform Tools (Beta)](https://plugins.jetbrains.com/plugin/10698-google-sceneform-tools-beta-)
OR
[Download Google Sceneform Tools Plugin](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=48349)

Step - 3: Install that plugin which you have download from above give link page. To install plugin follow below steps.
Go to File menu -> Settings -> Plugins and click on Install plugin from Disk.. and select path where plugin downloaded in your PC.

Restart after installing plugin and enjoy it.

**Comment by HEMAL-VES** [comment]
Hi 

There is a new update for google scene form tool with version number 1.6.0. And I have tried to update it from version 1.4.0 to 1.6.0. But still, android studio stops working and crash after updating and restart it. Again I try to open the android studio, it did not open.

The still crash issue is not resolved. Is anyone get the same issue?

**Comment by HEMAL-VES** [comment]
Couldn't create Engine
java.lang.IllegalStateException: Couldn't create Engine
	at com.google.android.filament.Engine.create(Engine.java:37)
	at com.google.ar.sceneform.filament.wrapper.Engine.create(Engine.java:14)
	at com.google.ar.sceneform.plugin.viewer.Filament$3.run(Filament.java:188)

I am getting above error when open android studio every time. My android studio details are as below:

- Android Studio v 3.2.1
- Google Sceneform Tool (beta) 1.4.0 (Note: I am not updating this plugin as Android Studio Crash after updating it with a new version (1.5.0 or 1.6.0))
- Windows 10 Pro (64 bit)
- RAM: 6GB
- Processor: Intel Core i3 - 3210 CPU (3.20 GHz)

And in a viewer, I am not able to see the preview of the 3D object which we have created using Google Sceneform Tools for files (sfa and sfb).

**Comment by samigehi** [comment]
Having same issue when installing Google Sceneform Tools (Beta) (1.7.0) with Android Studio 3.3.1, but it works perfect with 1.4.0 

[ref](https://github.com/google-ar/sceneform-android-sdk/issues/409#issuecomment-443191764)

@HEMAL-PATEL

**Comment by HEMAL-PATEL** [comment]
> Having same issue when installing Google Sceneform Tools (Beta) (1.7.0) with Android Studio 3.3.1, but it works perfect with 1.4.0
> 
> [ref](https://github.com/google-ar/sceneform-android-sdk/issues/409#issuecomment-443191764)
> 
> @HEMAL-PATEL

@samigehi 

That's right we are not able to update it from version 1.4.0 in Windows OS. While I tried it in Mac OS it updated and android studio open after updating it without a crash.

**Comment by michaelvogt** [comment]
Im using the plug-in without problems on Windows 10. Never had any crashes - but many other problems 😒

**Comment by HEMAL-PATEL** [comment]
> I'm using the plug-in without problems on Windows 10. Never had any crashes - but many other problems 😒

@michaelvogt 

But I am getting this issue in Windows 10 as early mention configurations. Android Studio crashed after updating that plugin from version 1.4.0 to latest one.

**Comment by samigehi** [comment]
Yes there is compatibility issue with latest version of android studio and win 10, when I update plugin to 1.6 or 1.7 even Android Studio wouldn't start. 😒

**Comment by michaelvogt** [comment]
I had to use the plugin today, and it worked as always. Which means its a annoying like hell until it does what it should.

But, I don't have crashes. So I wonder, what's different between our environments.

I have: 
Windows 10 (japanese)
Always available AS betas. Which is currently 3.4 beta4
Java that comes with AS
Always the Gradle requested by AS, currently 5.1.1
ARCore and Sceneform 1.7

**Comment by HEMAL-PATEL** [comment]
> I had to use the plugin today, and it worked as always. Which means its a annoying like hell until it does what it should.
> 
> But, I don't have crashes. So I wonder, what's different between our environments.
> 
> I have:
> Windows 10 (japanese)
> Always available AS betas. Which is currently 3.4 beta4
> Java that comes with AS
> Always the Gradle requested by AS, currently 5.1.1
> ARCore and Sceneform 1.7

I have below configuration for my PC.:

- OS: Windows 10 Pro (64 bit)
- Android Studio: 3.3.1 (Stable)
- RAM: 6GB
- Processor: Intel Core i3 - 3210 CPU (3.20 GHz)
- Sceneform Tool: 1.4.0 (Not using latest one as android studio crashed after updating it)
- ARCore: Latest 1.6.0
- JDK - 8u201

**Comment by HEMAL-PATEL** [comment]
Hi
@michaelvogt 

Is there any solution to resolve the crash issue. Because today I am trying a new thing to resolve the crash issue but it couldn't resolve. Still, android studio crashed. The way I am trying is as below:

1. First I updated my JDK from version 1.8.0_65 to 1.8.0_101. Then I tried to update the plugin and then restart android studio which crashed after restarted.

2. Then again I updated my JDK from version 1.8.0_101 to 1.8.0_201. Then tried to install the latest plugin and still crashed. Then I again tried to install old plugin version 1.5.0 and 1.6.0 but for that two plugins, it still crashed. 

I did not crash only when I install 1.4.0 plugin and works fine.

Please help me to resolve this issue.

**Comment by michaelvogt** [comment]
@HEMAL-PATEL I'd be happy to help, but I don't know enough about gradle plugins to debug them.

My suggestion would be to avoid this plugin, because even when its not crashing, it is very creative in finding all sorts of other trouble. I personally will definitely use gltf models in the future (when materials can finally be created programmatically), which can be imported directly. While this importer also has its problems, there is some interesting work happening for filament,  that should make the gltf import work much better (they say).

When you need the plugin, I would probably make sure that sceneform and the plugin are the same version. Then I wonder if the project loads with all the sceneform.asset entries removed. Does it crash when adding a certain model as an sceneform.asset, or does it crash with any model?

**Comment by yaserozhol** [comment]
> سلام
> 
> یک بروزرسانی جدید برای ابزار فرم صحنه گوگل با نسخه 1.6.0 وجود دارد. و من سعی کردم آن را از نسخه 1.4.0 تا 1.6.0 به روز کنم. اما هنوز، استودیوی آندروید پس از به روز رسانی و راه اندازی مجدد آن، کار می کند و سقوط می کند. باز هم من سعی می کنم استودیو اندیشه را باز کند، باز نشد.
> 
> هنوز موضوع تصادف حل نشده است. آیا کسی همان مسئله را دریافت می کند؟

hello, yes

**Comment by HEMAL-PATEL** [comment]
> > Hello
> > There is a new upgrade to the Google Stage Form Tool with version 1.6.0. And I tried to update it from version 1.4.0 to 1.6.0. But still, the Android studio works and falls after it's upgraded and restarted. Again, I try to open the Android Studio, it did not open.
> > Crash issue still not resolved. Does anyone receive the same issue?
> 
> hello, yes

Yes many developers are still getting same issue. Even with latest one version of 1.7.0 or 1.8.0.

**Comment by rastogitech** [comment]
Same issue with Android Studio 3.4.1 and SceneFormPlugin 1.9.0 (beta).

**Comment by HEMAL-PATEL** [comment]
> Same issue with Android Studio 3.4.1 and SceneFormPlugin 1.9.0 (beta). Don't know why new versions are being released without this major crash fix.

That's right @rastogitech 

Still facing many problems due to this issue. Not be able to use a new feature of this new latest tool.

**Comment by Barathwaja** [comment]
Yes am still facing this problem. Using Android Studio 3.4 with Sceneform Plugin 2.9

**Comment by Satish2804** [comment]
Still crashing.  Using Android Studio 3.4.2 with the sceneform plugin 1.10

**Comment by HEMAL-PATEL** [comment]
> Still crashing. Using Android Studio 3.4.2 with the sceneform plugin 1.10

Thats right. Nothing improvement from version 1.5 to 1.10. Android Studio crashed while updating from 1.4 to latest vestion.

**Comment by Satish2804** [comment]
Hi @michaelvogt ,

**Comment by Satish2804** [comment]
Hi @michaelvogt,

                      Why this issue is not resolved yet. We are unable to check model configurations before running the app.  Apart from that every time importing the assets is getting the problem.

**Comment by Satish2804** [comment]
Hi @michaelvogt,  Why this issue is not resolved yet. We are unable to check model configurations before running the app.  Apart from that every time importing the assets is getting the problem.

**Comment by michaelvogt** [comment]
@Satish2804
As I don't work for Google, I don't know. Activity around ARCore and Sceneform in general has been low (practically non existent). 

They even didn't see it necessary to announce some catch-up features as they did so far.

**Comment by Satish2804** [comment]
> @Satish2804
> As I don't work for Google, I don't know. Activity around ARCore and Sceneform, in general, has been low (practically non-existent).
> 
> They even didn't see it necessary to announce some catch-up features as they did so far.

 @michaelvogt  Sorry for misunderstanding you as a google developer and Thanks for the info.

**Comment by chnouman** [comment]
facing same issue. android studio gets close while loading project.

**Comment by HEMAL-PATEL** [comment]
> facing same issue. android studio gets close while loading project.

@chnouman Try to use the latest version of Android Studio with latest version of Sceneform plugin. In my PC that issue is resolved after installing latest version of Android Studio.

Before installing the latest version of Android Studio, first of uninstalling Android Studio completely (remove .AndroidStudio3.4 or other files).

Android Studio - v3.5
Sceneform Plugin - v1.12.0

**Comment by chnouman** [comment]
@HEMAL-PATEL  I resolved this issue by simply removing the project from the path from where the android studio was loading it and placed it on another location. Then tried to open android studio it opened up normally. Again I open a project from a new location and it works. Don't know technical reason behind it.

**Comment by erronblackk** [comment]
@HEMAL-PATEL thank you man you saved my day
