### ISSUE TITLE
Android studio is crashing with this error message

### ISSUE THREAD

**Issue by AbhishekPantUK** [google-ar/sceneform-android-sdk#411]
Error Message "Couldn't create Engine"
Couldn't create Engine
java.lang.IllegalStateException: Couldn't create Engine
at com.google.android.filament.Engine.create(Engine.java:37)
at com.google.ar.sceneform.filament.wrapper.Engine.create(Engine.java:14)
at com.google.ar.sceneform.plugin.viewer.Filament$3.run(Filament.java:192)

**Comment by tpsiaki** [comment]
Hi, did you recently upgrade or install the Sceneform plugin for the first time?  Which OS and version of Android Studio are you running?

**Comment by AbhishekPantUK** [comment]
Hi, I have install Scenform plugin for first time, I am using Android Studio 3.2.1 and ubuntu 14.04 LTS.

**Comment by HEMAL-VES** [comment]
Hi,

I am using android studio _version 3.1.4_. When I am updating **Google SceneForm Tools(Beta)** plugin from 1.4.0 to 1.5.0, android studio stop working in Windows. I have also try to update Android Studio with the latest version (3.2.0 / 3.2.1) but the same issue occurred android studio stop working. 

My PC Configuration is as below:
OS: Windows 10 Pro (64 bit)
RAM: 6GB
Processor: Intel Core i3 - 3210 CPU (3.20 GHz)

Android Studio: 3.1.4
Google SceneForm Tool: 1.4.0

Please help me to resolve this issue.

**Comment by tpsiaki** [comment]
@HEMAL-VES - What is the error message you are getting when you try to launch on Windows?  Is it the same one as reported above in this issue?

**Comment by HEMAL-VES** [comment]
> @HEMAL-VES - What is the error message you are getting when you try to launch on Windows? Is it the same one as reported above in this issue?

I am not getting any error message. It just shows that android studio stops working with close program option. And not be able to open android studio.

Yesterday I have just updated Android Studio to the latest version and install Google SceneForm Tool plugin version 1.4.0 which works fines but when I am updating it to the latest version (1.5.0) Android Studio stops working.

**Comment by Qenawi** [comment]
i had the same problem and solved it by resting android studio like follow -
why Sceneform plugin 
fix 
delete android studio 3.x file in  C:\Users\"username" and lunch android as normal 
and disable Sceneform plugin

**Comment by HEMAL-VES** [comment]
> I had the same problem and solved it by resting android studio like follow -
> bug cause-> Scene from a plugin
> bug fix->
> delete android studio 3.x file in C:\Users " username" and lunch android as normal
> and disable the Scene from a plugin

I have also tried this way but It does not work. So, I just update Android Studio to 3.2.1 version and added Sceneform plugin with a version of 1.4.0 which works fine.

**Comment by HEMAL-VES** [comment]
There is one more issue with Scene from a plugin. As Sceneform plugin shows the preview of the 3D object in the viewer. I am not able to show preview file for any 3D object. This issue occurs on any version of the android studio after 3.1.0 and any version of scene from plugin

**Comment by jamie-kb** [comment]
I'm having the same issue as mistrydarshan99, with the beta and 1.4 versions of Sceneform. Running on Debian 9 with a new install of everything.

**Comment by babasuresh** [comment]
Was anyone able to resolve it??

I am also facing similar issue on my Mac machine.
I have Android studio 3.3 and Sceneform plugin version 1.6. 

Android Studio crashes multiple times with same exception.
And whenever it runs, I can not see any preview for my 3D assets. 
Whenever I try to open model, Android Studio says there is fatal error and following exceptions can be seen:
`java.lang.IllegalStateException: Couldn't create Engine
	at com.google.android.filament.Engine.create(Engine.java:37)
	at com.google.ar.sceneform.filament.wrapper.Engine.create(Engine.java:18)
	at com.google.ar.sceneform.plugin.viewer.Filamentor$3.run(Filamentor.java:191)`

Then it will ask to disable Sceneform plugin.

**Comment by HEMAL-VES** [comment]
> Was anyone able to resolve it??
> 
> I am also facing similar issue on my Mac machine.
> I have Android studio 3.3 and Sceneform plugin version 1.6.
> 
> Android Studio crashes multiple times with same exception.
> And whenever it runs, I can not see any preview for my 3D assets.
> Whenever I try to open model, Android Studio says there is fatal error and following exceptions can be seen:
> `java.lang.IllegalStateException: Couldn't create Engine at com.google.android.filament.Engine.create(Engine.java:37) at com.google.ar.sceneform.filament.wrapper.Engine.create(Engine.java:18) at com.google.ar.sceneform.plugin.viewer.Filamentor$3.run(Filamentor.java:191)`
> 
> Then it will ask to disable Sceneform plugin.

Hello @babasuresh ,

The solution is that you have to downgrade Sceneform plugin with version 1.4.0 in which Android Studio will not crash. The version after 1.4.0 version can not be used as Android Studio will crash. 

For resolving your crash issue and downgrade Sceneform plugin [folllow instruction](https://github.com/google-ar/sceneform-android-sdk/issues/409#issuecomment-443191764) which I mention on another issue #409

**Comment by dabcmexpertise** [comment]
For Ubuntu users, Go to Home Directory, Search for .androidstudio 3.5 or related versions. Goto Plugins and search for sceneform plugin. Remove that folder and restart IDE. And Thank me to save your precious time!
