### ISSUE TITLE
Enable horizontal plane detection only

### ISSUE THREAD

**Issue by EdwinMurari** [google-ar/sceneform-android-sdk#434]
How can I enable horizontal plane detection only?
I tried this in onCreate function of my activity : 
`

try {

            Session session = new Session(this);

            Config config = new Config(session);
            config.setPlaneFindingMode(Config.PlaneFindingMode.HORIZONTAL);
            config.setUpdateMode(Config.UpdateMode.LATEST_CAMERA_IMAGE);
            arFragment.getArSceneView().setupSession(session);
        } catch (UnavailableArcoreNotInstalledException | UnavailableApkTooOldException | UnavailableSdkTooOldException e) {
            e.printStackTrace();
        }`

This give me the following error : 
`java.lang.RuntimeException: Invalid ARCore UpdateMode BLOCKING, Sceneform requires that the ARCore session is configured to the UpdateMode LATEST_CAMERA_IMAGE.
        at com.google.ar.sceneform.ArSceneView.ensureUpdateMode(Unknown Source)
        at com.google.ar.sceneform.ArSceneView.onBeginFrame(Unknown Source)
        at com.google.ar.sceneform.SceneView.doFrame(Unknown Source)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:618)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`
Thank you.

**Comment by EdwinMurari** [comment]
If anyone needs this, refer to [#362](https://github.com/google-ar/sceneform-android-sdk/issues/362)
