### ISSUE TITLE
IllegalArgumentException when using RenderableSource.builder()

### ISSUE THREAD

**Issue by itanbp** [google-ar/sceneform-android-sdk#453]
Hi,
I'm using `RenderableSource.builder()` for gltf files, and I receive `IllegalArgumentException` when the gltf file name has space in it.
For example see `1226 Moon.gltf` from [poly](https://poly.google.com/view/9OPocAqXM0u).

Full error:
java.lang.IllegalArgumentException: Illegal character in path at index 6: ./1226 Moon.bin

**Comment by jimmod** [comment]
I encounter same issue with `version 1.12.0`
From the crash pattern it happen when the URL having an encoded unsafe ASCII characters such as `%20`

code snippet:
```
 GlobalScope.launch(Dispatchers.Main) {
                ModelRenderable.builder()
                    .setSource(
                        context,
                        RenderableSource.builder()
                            .setSource(
                                context,
                            Uri.parse("https://poly.googleapis.com/downloads/fp/1571824837180764/b0N_HeT_Ttb/1-u-viSZ0Ue/1352%20Flying%20Saucer.gltf"),
                                RenderableSource.SourceType.GLTF2
                            )
                            .build()
                    )
                    .build()
                    .thenAccept {  }
```

Stack-trace:
```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Illegal character in path at index 6: ./1352 Flying Saucer.bin
        at com.google.ar.sceneform.utilities.SceneformBufferUtils.inputStreamToByteBuffer(SourceFile:49)
        at com.google.ar.sceneform.rendering.LoadRenderableFromSfbTask.lambda$downloadAndProcessRenderable$0$LoadRenderableFromSfbTask(LoadRenderableFromSfbTask.java:118)
        at com.google.ar.sceneform.rendering.-$$Lambda$LoadRenderableFromSfbTask$0DkaOpfpmr8DYlbaxWogZtUpKTw.get(Unknown Source:4)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1625)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 6: ./1352 Flying Saucer.bin
        at java.net.URI.create(URI.java:848)
        at java.net.URI.resolve(URI.java:1032)
        at com.google.ar.sceneform.assets.RenderableSource.call(Unknown Source:157)
        at com.google.ar.sceneform.assets.RenderableSource.call(Unknown Source:0)
        at com.google.ar.sceneform.utilities.SceneformBufferUtils.inputStreamToByteBuffer(SourceFile:42)
        at com.google.ar.sceneform.rendering.LoadRenderableFromSfbTask.lambda$downloadAndProcessRenderable$0$LoadRenderableFromSfbTask(LoadRenderableFromSfbTask.java:118) 
        at com.google.ar.sceneform.rendering.-$$Lambda$LoadRenderableFromSfbTask$0DkaOpfpmr8DYlbaxWogZtUpKTw.get(Unknown Source:4) 
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1625) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.net.URISyntaxException: Illegal character in path at index 6: ./1352 Flying Saucer.bin
        at java.net.URI$Parser.fail(URI.java:2893)
        at java.net.URI$Parser.checkChars(URI.java:3066)
        at java.net.URI$Parser.parseHierarchical(URI.java:3150)
        at java.net.URI$Parser.parse(URI.java:3108)
        at java.net.URI.<init>(URI.java:584)
```
