### ISSUE TITLE
RuntimeException: ManagedChannel allocation site (Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true)

### ISSUE THREAD

**Issue by codeniko** [google-ar/sceneform-android-sdk#466]
I'm not sure yet how to reproduce this but it happened after coming back into the AR camera activity after placing app in background, and turning off screen for a couple mins, then coming back and opening app again.

```text
2018-12-14 14:31:23.736 6736-6736/? E/bsh: *~*~*~ Channel {0} was not shutdown properly!!! ~*~*~*
        Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
    java.lang.RuntimeException: ManagedChannel allocation site
        at bsi.<init>(PG:4)
        at bsh.<init>(PG:4)
        at bsh.<init>(PG:1)
        at bll.a(PG:55)
        at com.google.ar.persistence.AnchorServiceClientFactory.create(PG:21)
        at com.google.ar.core.Session.nativeCreateSession(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:5)
        at com.google.ar.sceneform.ux.BaseArFragment.initializeSession(BaseArFragment.java:329)
        at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:297)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3212)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:217)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
        at android.app.Activity.performResume(Activity.java:7377)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3763)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3036)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by bigant88** [comment]
the same issue is here https://github.com/google-ar/arcore-android-sdk/issues/637
