### ISSUE TITLE
Crash: Unable to create RenderableInstance.

### ISSUE THREAD

**Issue by tpearson1** [google-ar/sceneform-android-sdk#472]
I've been working on an AR app, which involves creation of a fence. I'm using a model and I am placing multiple instances of the model with some separation between. When I'm creating the fence in the app, the app often crashes. Here's the exception:

```
2018-12-19 17:23:19.054 12295-12295/? D/AndroidRuntime: Shutting down VM
2018-12-19 17:23:19.056 12295-12295/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <our app>, PID: 12295
    java.lang.AssertionError: Unable to create RenderableInstance.
        at com.google.ar.sceneform.rendering.RenderableInstance.buildInstanceData(RenderableInstance.java:245)
        at com.google.ar.sceneform.rendering.RenderableInstance.prepareForDraw(RenderableInstance.java:142)
        at com.google.ar.sceneform.rendering.Renderer.updateInstances(Renderer.java:424)
        at com.google.ar.sceneform.rendering.Renderer.render(Renderer.java:190)
        at com.google.ar.sceneform.SceneView.doRender(Unknown Source:16)
        at com.google.ar.sceneform.SceneView.doFrame(Unknown Source:25)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Does anybody know why this might be happening?

**Comment by tpearson1** [comment]
Here's a full [log](https://gist.github.com/tpearson1/dfaa92a51c1a2da873a1c0f8a1140e43). I hope this helps.

**Comment by claywilkinson** [comment]
Thanks - Nothing jumped out as a root cause -I'll pass it along for a closer look.

**Comment by tpearson1** [comment]
Hi, do we have a progress update? Thanks.

**Comment by tpearson1** [comment]
It may be due to the large number of instances of a certain model being produced (~80), but if so the error message should be clearer.
