### ISSUE TITLE
More graceful error than crashing if ABI jni library isn't available?

### ISSUE THREAD

**Issue by kenyee** [google-ar/sceneform-android-sdk#512]
Saw this odd stack trace in the field.

We only specify arm64-v8a with the abiFilters to try and get this only on the newest
I think this device is armeabi-v7a...trying to get more info from the user.
But shouldn't the SceneForm runtime do a check that the Filament binary shared library is available before trying to use it and blowing up?

```
01-25 10:13:59.600 E/AndroidRuntime( 3489): java.lang.NoClassDefFoundError: com.google.android.filament.Filament
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.android.filament.Filament.init(Unknown Source:0)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.EngineInstance.createEngine(SourceFile:50)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.EngineInstance.getEngine(SourceFile:23)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.RenderableInternalData.n(SourceFile:175)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.RenderableInternalData.o(SourceFile:159)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.RenderableInternalData.lambda$K513CKMiTYyLSeMLGFafKLjBQDI(Unknown Source:0)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.-$$Lambda$RenderableInternalData$K513CKMiTYyLSeMLGFafKLjBQDI.run(Unknown Source:2)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at android.os.Handler.handleCallback(Handler.java:891)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at android.os.Looper.loop(Looper.java:207)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at android.app.ActivityThread.main(ActivityThread.java:7470)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at java.lang.reflect.Method.invoke(Native Method)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.huawei.secdroid.hook.MethodLoaderBridge.main(MethodLoaderBridge.java:159)
01-25 10:13:59.600 E/AndroidRuntime( 3489): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/hw_init/product/region_comm/oversea/app/KAYAK/KAYAK-kayakFree-release-71.0-1262-20190115.apk"],nativeLibraryDirectories=[/data/hw_init/product/region_comm/oversea/app/KAYAK/lib/arm64, /data/hw_init/product/region_comm/oversea/app/KAYAK/KAYAK-kayakFree-release-71.0-1262-20190115.apk!/lib/arm64-v8a, /system/lib64, /product/lib64, /system/lib64, /product/lib64]]] couldn't find "libfilament-jni.so"
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at java.lang.System.loadLibrary(System.java:1672)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.android.filament.Filament.<clinit>(SourceFile:22)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.android.filament.Filament.init(Unknown Source:0)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.EngineInstance.createEngine(SourceFile:50)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.EngineInstance.getEngine(SourceFile:23)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.c.a(SourceFile:240)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.c.d(SourceFile:232)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.c.h(SourceFile:140)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.c.lambda$zU8r4SjwtpQRLCCCmMQs5U4eI4c(Unknown Source:0)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at com.google.ar.sceneform.rendering.-$$Lambda$c$zU8r4SjwtpQRLCCCmMQs5U4eI4c.apply(Unknown Source:4)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:610)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:585)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:450)
01-25 10:13:59.600 E/AndroidRuntime( 3489): 	... 8 more
```

**Comment by kenyee** [comment]
Possibly related to: https://github.com/google-ar/arcore-android-sdk/issues/646
Device in the field from a crashlytics report is a Huawei PAR-LX9 (Nova 3) running Android Pie (9.0):

```
Caused by java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/hw_init/product/region_comm/oversea/app/KAYAK/KAYAK-kayakFree-release-71.0-1262-20190115.apk"],nativeLibraryDirectories=[/data/hw_init/product/region_comm/oversea/app/KAYAK/lib/arm64, /data/hw_init/product/region_comm/oversea/app/KAYAK/KAYAK-kayakFree-release-71.0-1262-20190115.apk!/lib/arm64-v8a, /system/lib64, /product/lib64, /system/lib64, /product/lib64]]] couldn't find "libfilament-jni.so"
```
