### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by underworld9** [google-ar/sceneform-android-sdk#538]
I've fixed this in our codebase. This did not make the 1.6.0 release train however so will be in a release after that.

_Originally posted by @malik-at-work in https://github.com/google-ar/sceneform-android-sdk/issues/413#issuecomment-444289518_

**Comment by artemtkachenko** [comment]
@underworld9 

I am experiencing the same issue. 
The `hellosceneform` profile results. I launched and finished several HelloSceneformActivities one by one. And all of the objects: `Camera` `Texture` `Scene` remains in memory after forcing GC:
https://monosnap.com/file/ewEPKAHXgPRDQRo6JhGRwCuXhcZutl 
These objects holds an an `ArSceneView` that is why HelloSceneformActivitiy leaked.

Moreover I found that with using `asyncPause()` feature my Pixel3 reports an error: 
```
E/ACameraDevice: onDeviceIdle sending state cb
E/ActivityThread: Activity %app_package_my_activity% has leaked ServiceConnection apy@e18bb27 that was originally bound here
android.app.ServiceConnectionLeaked: Activity %app_package_my_activity% has leaked ServiceConnection apy@e18bb27 that was originally bound here
at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1610)
at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1502)
at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1659)
at android.app.ContextImpl.bindService(ContextImpl.java:1612)
at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
at com.google.ar.core.services.AnalyticsClient.bindService(PG:30)
at com.google.ar.core.Session.nativeCreateSessionWithFeatures(Native Method)
at com.google.ar.core.Session.<init>(Session.java:23)
```

It seems that all the samples and scene-form itself was not designed for releasing resources.
