### ISSUE TITLE
Sceneform Android Studio Plugin: Couldn't create Engine

### ISSUE THREAD

**Issue by dosur** [google-ar/sceneform-android-sdk#602]
java.lang.IllegalStateException: Couldn't create Engine
	at com.google.android.filament.Engine.create(Engine.java:37)
	at com.google.ar.sceneform.plugin.viewer.Filamentor$3.run(Filamentor.java:102)

**Comment by fredsa** [comment]
Closing as this issue is missing key information to help us reproduce it.
- Android Studio version
- Sceneform version
- Device manufacturer, model, and O/S
- ARCore APK installed version:
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell pm path com.google.ar.core`
- Output of `adb shell getprop ro.build.fingerprint`
- Specific error message or problem encountered

**Comment by tpsiaki** [comment]
It looks like the crash you're reporting is in the Android Studio plugin.  It would be helpful to share the Android Studio version, the platform you're running (OS, version), and what the repro is (my assumption is it gives you this error message on startup).

It would also be helpful to share some logs from the issue.  After restarting Android Studio with the plugin enabled and triggering the crash/error, go to Help > Collect and show logs in Finder (or explorer if Windows), and share at least the most recent idea.log file.  Feel free to send them via email if you'd prefer to share them that way.

**Comment by dosur** [comment]
thank for your concernhere some screenshoot attachedtool : Android Studio 3.3.2disable & Restarting the plugin cast solve the problem (sceneform 1.7.0 & 1.8.0)3d model cant be viewed in sceneform viewer

    On Friday, March 29, 2019, 1:17:38 AM GMT+7, tpsiaki <notifications@github.com> wrote:  
 
 
It looks like the crash you're reporting is in the Android Studio plugin. It would be helpful to share the Android Studio version, the platform you're running (OS, version), and what the repro is (my assumption is it gives you this error message on startup).

It would also be helpful to share some logs from the issue. After restarting Android Studio with the plugin enabled and triggering the crash/error, go to Help > Collect and show logs in Finder (or explorer if Windows), and share at least the most recent idea.log file. Feel free to send them via email if you'd prefer to share them that way.
