### ISSUE TITLE
createAnchor crashes the application

### ISSUE THREAD

**Issue by zqin97** [google-ar/sceneform-android-sdk#653]
I'm trying to show a marker in front of my device, however createAnchor always crashes my application and I don't know what is wrong with it, below following is my code:
`        fragment = (ARFragment) getSupportFragmentManager().findFragmentById(R.id.sceneform_fragment);

        // When you build a Renderable, Sceneform loads its resources in the background while returning
        // a CompletableFuture. Call thenAccept(), handle(), or check isDone() before calling get().
        ModelRenderable.builder()
                .setSource(this, Uri.parse("marker.sfb"))
                .build()
                .thenAccept(renderable -> markerRenderable = renderable)
                .exceptionally(
                        throwable -> {
                            Toast toast =
                                    Toast.makeText(this, "Unable to load andy renderable", Toast.LENGTH_LONG);
                            toast.setGravity(Gravity.CENTER, 0, 0);
                            toast.show();
                            return null;
                        });

        Session session = fragment.getArSceneView().getSession();
        float[] pos = { (float)deviceLocation.getLatitude(),(float)deviceLocation.getLatitude(), 0};
        float[] rotation = {0,0,0,1};
        Anchor anchor = session.createAnchor(new Pose(pos, rotation));
        AnchorNode anchorNode = new AnchorNode(anchor);
        anchorNode.setParent(fragment.getArSceneView().getScene());

        // Create the transformable marker and add it to the anchor.
        TransformableNode marker = new TransformableNode(fragment.getTransformationSystem());
        marker.setParent(anchorNode);
        marker.setRenderable(markerRenderable);
        marker.select();`

**Comment by ishaang10** [comment]
please share your log ..

**Comment by zqin97** [comment]
@ishaang10 

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ar.navi, PID: 3178
    com.google.ar.core.exceptions.NotTrackingException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:134)
        at com.google.ar.core.Session.nativeCreateAnchor(Native Method)
        at com.google.ar.core.Session.createAnchor(Session.java:93)
        at ar.navi.NavigationActivity.onUpdateFrame(NavigationActivity.java:399)
        at ar.navi.NavigationActivity.lambda$FIwIbGK7jEe3MIwRgZ1gZxUsanY(Unknown Source:0)
        at ar.navi.-$$Lambda$NavigationActivity$FIwIbGK7jEe3MIwRgZ1gZxUsanY.onUpdate(Unknown Source:2)
        at com.google.ar.sceneform.Scene.dispatchUpdate(SourceFile:111)
        at com.google.ar.sceneform.SceneView.doUpdate(SourceFile:98)
        at com.google.ar.sceneform.SceneView.doFrame(SourceFile:84)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1077)
        at android.view.Choreographer.doCallbacks(Choreographer.java:885)
        at android.view.Choreographer.doFrame(Choreographer.java:806)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1065)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)`

**Comment by ishaang10** [comment]
you have added tge ARfragment right?

**Comment by zqin97** [comment]
@ishaang10 can you tell me what I should provide? I not sure what is a log

**Comment by dashifuguye** [comment]
hi, zqin97, i meet the same crash when createAnchor(), have you solve it? what is the roor cause?
