### ISSUE TITLE
Opening an ARFragment consecutive times causes MissingGLContextException

### ISSUE THREAD

**Issue by vicgrad** [google-ar/sceneform-android-sdk#683]
I have slightly modified the Augmented Images sample to have another activity in front that starts the AR experience. When I close and open the AugmentedImageActivity the second time it crashes with MissingGlContextException:

E/native: status.cc:156 ArStatusErrorSpace::AR_ERROR_MISSING_GL_CONTEXT: 
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mk.whatsnextandroid, PID: 28243
    com.google.ar.core.exceptions.MissingGlContextException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:134)
        at com.google.ar.core.Session.nativeUpdate(Native Method)
        at com.google.ar.core.Session.update(Session.java:74)
        at com.google.ar.sceneform.ArSceneView.onBeginFrame(SourceFile:94)
        at com.google.ar.sceneform.SceneView.doFrame(SourceFile:83)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Testing on Pixel 3, sceneform 1.8.0

**Comment by vicgrad** [comment]
The only thing I could do to work around this is to open the ar activity as a separate process.

**Comment by drummor** [comment]
about single instance?

**Comment by Arlem** [comment]
I had the same issue, in my case there was an initialization with a custom webview.

Have you tried to reproduce with an empty activity?

**Comment by Moneera** [comment]
I have the same problem, when I run the activity alone, it works just fine. But when I open it from another activity, a nullpointerexception appears in arFragment.setOnTapArPlaneListener((hitResult, plane, motionEvent) method (which is inside onCreate method), any ideas what should I do?
