### ISSUE TITLE
Memory leak leading to rendering errors

### ISSUE THREAD

**Issue by LDuncAndroid** [google-ar/sceneform-android-sdk#719]
I have read #538 and I'm not sure if this issue is related, but the issue in #538 does occur.

My `ArSceneView` is the 2nd child of a `FrameLayout` that is inflated in a Custom View. The 1st child is another CustomView that contains a `SurfaceView`. The Custom View is a `LifecycleObserver` and when the `ON_DESTROY` event is triggered, the following is executed:

```
    @OnLifecycleEvent(Lifecycle.Event.ON_DESTROY)
    fun destroy() {
        arSceneView.destroy()
    }
```

`ON_PAUSE` looks like this:
```
    @OnLifecycleEvent(Lifecycle.Event.ON_PAUSE)
    fun pause() {
        arSceneView.pause()
    }
```

When rotating the device from portrait to landscape the `ArSceneView` no longer renders the camera, it's just a black screen, and the LogCat is filled with the following messages:

```
2019-05-30 14:55:10.309 27866-27866/${my.app.activity} W/GLConsumer: [SurfaceTexture-0-27866-2] bindTextureImage: clearing GL error: 0x501
2019-05-30 14:55:10.342 27866-27866/${my.app.activity} W/GLConsumer: [SurfaceTexture-0-27866-2] bindTextureImage: clearing GL error: 0x501
2019-05-30 14:55:10.358 27866-28468/${my.app.activity} W/native: vio_initializer.cc:337 Dropped initialization window due to invalid IMU measurements.
```

### LogCat
```
2019-05-30 14:55:07.668 27866-28153/${my.app.activity} I/native: cameras.cc:720 Camera changed state from 4 to 1: Capture session finished streaming.
2019-05-30 14:55:07.669 27866-28159/${my.app.activity} I/native: android_camera.cc:1071 Capture sequence completed.
2019-05-30 14:55:07.745 27866-28159/${my.app.activity} I/native: android_camera.cc:1019 Capture session closed for camera 0
2019-05-30 14:55:07.855 27866-27866/${my.app.activity} I/native: android_camera.cc:524 Reset cleanly got to CLOSED state for camera 0
2019-05-30 14:55:07.856 27866-28153/${my.app.activity} I/native: cameras.cc:720 Camera changed state from 1 to 0: Camera device closed successfully.
2019-05-30 14:55:07.861 27866-27866/${my.app.activity} I/native: session.cc:987 Session::Pause returning OK.
2019-05-30 14:55:07.915 27866-27866/${my.app.activity} E/WindowManager: android.view.WindowLeaked: Activity ${my.app.activity}.test.sceneview.SceneViewActivity has leaked window android.widget.FrameLayout{d5a8458 V.E...... ......I. 0,0-0,0} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:530)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at com.google.ar.sceneform.rendering.ViewAttachmentManager.lambda$onResume$0$ViewAttachmentManager(ViewAttachmentManager.java:64)
        at com.google.ar.sceneform.rendering.-$$Lambda$ViewAttachmentManager$zHzKkfBniDn8VWbgoIAhBR19Pac.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6923)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
2019-05-30 14:55:08.001 27866-27866/${my.app.activity} I/SceneView: Optional library com.google.ar.sceneform.animation not present. Sceneform animation disabled
2019-05-30 14:55:08.106 27866-27866/${my.app.activity} I/third_party/arcore/ar/core/android/sdk/session_create.cc: Entering ArSession_create
2019-05-30 14:55:08.110 27866-27866/${my.app.activity} I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: APK version code: 190422056
2019-05-30 14:55:08.110 27866-27866/${my.app.activity} I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: SDK build name: 1.9
2019-05-30 14:55:08.114 27866-27866/${my.app.activity} I/native: version_check.cc:23 ARCore Version: APK version:1.9.190422056
2019-05-30 14:55:08.114 27866-27866/${my.app.activity} I/native: version_check.cc:24 ARCore Version: emulated SDK version:1.9.190412000
2019-05-30 14:55:08.114 27866-27866/${my.app.activity} I/third_party/arcore/ar/core/android/sdk/session_create.cc: Dynamite load ok.
2019-05-30 14:55:08.115 27866-27866/${my.app.activity} I/native: session_create_implementation.cc:64 Entering createImplementationWithFeaturesAndSettings. ARCore SDK version: [1.9.190412000].
2019-05-30 14:55:08.119 27866-28455/${my.app.activity} V/third_party/redwood/base/jni_common/jni_helper.cc: JniHelper: attached thread (Called from line 278).
2019-05-30 14:55:08.142 27866-27866/${my.app.activity} I/native: session_create_implementation_shared.cc:962 Persistent online recalibration is enabled by Phenotype.
2019-05-30 14:55:08.143 27866-27866/${my.app.activity} I/native: online_calibration_manager.cc:51 OnlineCalibrationManager: Could not open /data/user/0/${my.app.activity}/cache/arcore-online-recalibration for reading.
2019-05-30 14:55:08.148 27866-27866/${my.app.activity} I/native: feature_provider.cc:105 Doing adaptive frequency feature extraction using KLT.
2019-05-30 14:55:08.148 27866-27866/${my.app.activity} I/native: device_profile_conversions.cc:143 used_active_calibration: 2
2019-05-30 14:55:08.149 27866-27866/${my.app.activity} I/native: device_profile_conversions.cc:143 used_active_calibration: 2
2019-05-30 14:55:08.151 27866-27866/${my.app.activity} I/native: android_sensors.cc:83 Using calibrated accelerometer.
2019-05-30 14:55:08.152 27866-27866/${my.app.activity} I/native: android_sensors.cc:116 Using uncalibrated magnetometer.
2019-05-30 14:55:08.154 27866-27866/${my.app.activity} I/native: config_helpers.cc:207 Failed to find IMU intrinsic covariance matrix in profile for id: 100
2019-05-30 14:55:08.155 27866-27866/${my.app.activity} I/native: motion_tracking_context.cc:497 Legacy IMU sigma values are used
2019-05-30 14:55:08.155 27866-27866/${my.app.activity} I/native: config_helpers.cc:207 Failed to find IMU intrinsic covariance matrix in profile for id: 100
2019-05-30 14:55:08.155 27866-27866/${my.app.activity} I/native: calibration_provider.cc:998 Using default initial IMU intrinsic covariance matrix.
2019-05-30 14:55:08.155 27866-27866/${my.app.activity} I/native: config_helpers.cc:60 Does not find camera intrinsic covariance matrix in profile for id 0
2019-05-30 14:55:08.155 27866-27866/${my.app.activity} I/native: calibration_provider.cc:874 Using default initial camera intrinsic covariance matrix.
2019-05-30 14:55:08.155 27866-27866/${my.app.activity} I/native: config_helpers.cc:133 Does not find extrinsic covariance matrix in profile for IMU id 100
2019-05-30 14:55:08.155 27866-27866/${my.app.activity} I/native: calibration_provider.cc:936 Using default initial extrinsic covariance matrix.
2019-05-30 14:55:08.156 27866-27866/${my.app.activity} I/native: feature_matcher_and_filter.cc:125 Enabled the robustification to large-sized and fast-moving objects on this mono-camera device.
2019-05-30 14:55:08.158 27866-27866/${my.app.activity} I/native: vio_helper.cc:32 Use calibrated IMU scale factors.
2019-05-30 14:55:08.158 27866-27866/${my.app.activity} I/native: vio_helper.cc:44 Use calibrated IMU misalignment factors.
2019-05-30 14:55:08.298 27866-27866/${my.app.activity} I/native: android_platform_checks.cc:190 IsZeroRotationLandscape = false
2019-05-30 14:55:08.298 27866-27866/${my.app.activity} I/native: device_profile_conversions.cc:143 used_active_calibration: 2
2019-05-30 14:55:08.304 27866-27866/${my.app.activity} W/ARCore-ContextUtils: The API key for use with the Google AR service could not be obtained!
2019-05-30 14:55:08.317 27866-27866/${my.app.activity} I/native: android_camera.cc:1111 Initializing camera manager.
2019-05-30 14:55:08.321 27866-27866/${my.app.activity} I/native: android_camera.cc:1135 Camera manager initialized successfully with 3 cameras.
2019-05-30 14:55:08.321 27866-27866/${my.app.activity} I/native: session_create_implementation_shared.cc:1363 CPU Image enable frame delay to compensate delay: false
2019-05-30 14:55:08.333 27866-27866/${my.app.activity} I/native: session_create_implementation_shared.cc:508 AugmentedRegion downsample mode from Phenotype: true
2019-05-30 14:55:08.335 27866-27866/${my.app.activity} I/native: planar_target_tracking_manager.h:110 Config of PlanarTargetTrackingManager:
    -pose_refinement_with_detection_interval_ns: 0
    -min_interval_between_detections_ns: 500000000
    -filter_parallax: false
    -filter_result: true
    -multiple_targets: true
    -mini_detection: true
    -tracking_mode: 1
2019-05-30 14:55:08.354 27866-27866/${my.app.activity} I/native: session_create_implementation.cc:229 createImplementationWithFeaturesAndSettings returning OK.
2019-05-30 14:55:08.354 27866-27866/${my.app.activity} I/third_party/arcore/ar/core/android/sdk/arimage_jni.cc: Loading AImage symbols
2019-05-30 14:55:08.356 27866-27866/${my.app.activity} I/third_party/arcore/ar/core/android/sdk/image_metadata_jni.cc: Loading ACameraMetadata symbols
2019-05-30 14:55:08.388 27866-27866/${my.app.activity} I/native: session.cc:850 Entering Session::Resume.
2019-05-30 14:55:08.391 27866-27866/${my.app.activity} I/native: android_sensors.cc:139 Starting thread.
2019-05-30 14:55:08.391 27866-27866/${my.app.activity} I/native: cameras.cc:542 Selected camera 0 stream 0 as feature extraction stream.
2019-05-30 14:55:08.395 27866-28477/${my.app.activity} I/native: android_sensors.cc:28 Gyro min delay 5ms requesting 5ms
2019-05-30 14:55:08.410 27866-28477/${my.app.activity} I/native: android_sensors.cc:28 Accel min delay 5ms requesting 5ms
2019-05-30 14:55:08.465 27866-28473/${my.app.activity} I/native: cameras.cc:720 Camera changed state from 0 to 1: Camera device opened successfully.
2019-05-30 14:55:08.465 27866-28473/${my.app.activity} I/native: cameras.cc:720 Camera changed state from 1 to 2: Capture session starting...
2019-05-30 14:55:08.465 27866-28473/${my.app.activity} I/native: cameras.cc:720 Camera changed state from 2 to 3: Capture session started streaming.
2019-05-30 14:55:08.466 27866-27866/${my.app.activity} I/native: session.cc:913 Session::Resume returning OK.
2019-05-30 14:55:08.483 27866-27866/${my.app.activity} I/Choreographer: Skipped 58 frames!  The application may be doing too much work on its main thread.
2019-05-30 14:55:08.516 27866-27866/${my.app.activity} E/native: session.cc:1527 Invalid ray produced by view data!
2019-05-30 14:55:08.729 27866-28478/${my.app.activity} I/native: timebase_helpers.cc:168 Timebase offset intialized to 0
2019-05-30 14:55:08.781 27866-28467/${my.app.activity} W/native: gyro_helper.cc:44 Gyro samples do not cover << [ 0 ; 19718.9136058600016 ] sec. Use identity R. Gyro samples cover [ 19718.7220841919989 ; 19718.9809648075025 ] sec.
2019-05-30 14:55:08.782 27866-28468/${my.app.activity} I/native: vio_initializer.cc:620 Not accepting frame as first BA keyframe.
2019-05-30 14:55:08.863 27866-27866/${my.app.activity} W/GLConsumer: [SurfaceTexture-0-27866-2] bindTextureImage: clearing GL error: 0x501
2019-05-30 14:55:08.889 27866-28468/${my.app.activity} I/native: vio_initializer.cc:620 Not accepting frame as first BA keyframe.
2019-05-30 14:55:08.922 27866-27866/${my.app.activity} W/GLConsumer: [SurfaceTexture-0-27866-2] bindTextureImage: clearing GL error: 0x501
2019-05-30 14:55:08.969 27866-27879/${my.app.activity} I/runtime.toolki: Background concurrent copying GC freed 10754(1160KB) AllocSpace objects, 17(3MB) LOS objects, 49% free, 6MB/13MB, paused 525us total 118.497ms
2019-05-30 14:55:08.974 27866-28468/${my.app.activity} I/native: vio_initializer.cc:620 Not accepting frame as first BA keyframe.
2019-05-30 14:55:08.975 27866-27866/${my.app.activity} W/GLConsumer: [SurfaceTexture-0-27866-2] bindTextureImage: clearing GL error: 0x501
2019-05-30 14:55:09.025 27866-27866/${my.app.activity} W/GLConsumer: [SurfaceTexture-0-27866-2] bindTextureImage: clearing GL error: 0x501
```

**Comment by LDuncAndroid** [comment]
Closing as this may well be due to the rendering we perform on `GLSurfaceView` and an issue with destroying the GL Context. Doesn't appear to be related to a memory leak, though this memory leak still exists.
