### ISSUE TITLE
Model(target) expects to resample 0 bones; Animation(source) has 43 bones

### ISSUE THREAD

**Issue by Stefjs** [google-ar/sceneform-android-sdk#785]
Download .obj from Google Poly -> animate it using Mixamo -> download .fbx -> import it -> error.
I also tried to import it in Blender and then export .obj and .fbx but I still get the same error.

How can I export/import it correctly?

> java.lang.RuntimeException: Model(target) expects to resample 0 bones; Animation(source) has 43 bones
	at com.google.ar.sceneform.assets.AnimationInstance.nCreateAnimationTarget(Native Method)
	at com.google.ar.sceneform.assets.AnimationInstance.createTarget(AnimationInstance.java:23)
	at com.google.ar.sceneform.plugin.viewer.FilamentViewer.setupAnimation(FilamentViewer.java:124)
	at com.google.ar.sceneform.plugin.viewer.FilamentViewer.access$500(FilamentViewer.java:32)
	at com.google.ar.sceneform.plugin.viewer.FilamentViewer$1$1.run(FilamentViewer.java:97)
	at com.google.ar.sceneform.plugin.viewer.Filamentor$3.run(Filamentor.java:113)

EDIT: Also, when I import it using only a .fbx file then it seems to import correctly but as a result Android Studio crashes, and every time I try to open the .sfb file...

SECOND EDIT: The animation works but I still can't open the .sfb file without having Android Studio crash. So I cannot view my model and animations in the Viewer.

THIRD EDIT: If I import 2 animations and do getAnimationDataCount(); then it will only return 1. In the .sfa file I have 2 animations listed, why?

**Comment by Stefjs** [comment]
Used Autodesk Maya with the FBX asset format and requirements from here https://developers.google.com/ar/develop/java/sceneform/animation/obtaining-assets and it works now

Blender did not work for me
