### ISSUE TITLE
Latest update v1.11.0 broke Android Studio launch

### ISSUE THREAD

**Issue by iBog** [google-ar/sceneform-android-sdk#820]
![sceneform_err](https://user-images.githubusercontent.com/168304/62763834-28dd5c80-ba95-11e9-9003-4dde9fff76d5.jpg)

**Comment by iBog** [comment]
Log:
2019-08-09 10:56:45,358 [entQueue-0]  DEBUG -                com.crashlytics - *** Current updater: io.fabric.tools.androidstudio.plugin / io.fabric.tools.androidstudio.managed 
2019-08-09 10:56:45,361 [entQueue-0]   INFO - in.viewer.SceneformSFBProvider - Loading filament lib 
2019-08-09 10:56:45,437 [entQueue-0]   INFO - in.viewer.SceneformSFBProvider - Starting Filament 
2019-08-09 10:56:45,471 [ent-Thread]  ERROR - llij.ide.plugins.PluginManager - com.google.ar.sceneform.assets.Loader.nCreateAnimationPlayer()J 
java.lang.UnsatisfiedLinkError: com.google.ar.sceneform.assets.Loader.nCreateAnimationPlayer()J
	at com.google.ar.sceneform.assets.Loader.nCreateAnimationPlayer(Native Method)
	at com.google.ar.sceneform.assets.Loader.createAnimationPlayer(Loader.java:65)
	at com.google.ar.sceneform.plugin.viewer.Filamentor$3.run(Filamentor.java:105)
2019-08-09 10:56:45,472 [ent-Thread]  ERROR - llij.ide.plugins.PluginManager - Android Studio 3.5 RC 2  Build #AI-191.7479.19.35.5763348 
2019-08-09 10:56:45,472 [ent-Thread]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-08-09 10:56:45,472 [ent-Thread]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2019-08-09 10:56:45,509 [ent-Thread]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Google Sceneform Tools (Beta) version: 1.11.0

**Comment by TinyBuster1** [comment]
any solution ? got same problem.

**Comment by tpsiaki** [comment]
Thanks for the report.  We are working on a fix for the Sceneform Plugin.

**Comment by MMucahitDogan** [comment]
same problem

**Comment by TinyBuster1** [comment]
> Thanks for the report. We are working on a fix for the Sceneform Plugin.

in some video i found that a person got same bug, but on on his PC everything is fine, he said only only on laptop its not working but on home PC its all good, i didnt test it myself.

**Comment by tpsiaki** [comment]
We just released v1.11.1 which has the fix for this issue which occurred on Linux and Windows machines.
