### ISSUE TITLE
java.lang.AssertionError: Unable to create RenderableInstance

### ISSUE THREAD

**Issue by RGregat** [google-ar/sceneform-android-sdk#857]
Hi, I encounter arbitrary exceptions in my application.

```
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com........, PID: 16683
    java.lang.AssertionError: Unable to create RenderableInstance.
        at com.google.ar.sceneform.rendering.RenderableInternalData.buildInstanceData(RenderableInternalData.java:221)
        at com.google.ar.sceneform.rendering.RenderableInstance.prepareForDraw(RenderableInstance.java:161)
        at com.google.ar.sceneform.rendering.Renderer.updateInstances(Renderer.java:477)
        at com.google.ar.sceneform.rendering.Renderer.render(Renderer.java:210)
        at com.google.ar.sceneform.SceneView.doRender(SourceFile:112)
        at com.google.ar.sceneform.SceneView.doFrame(SourceFile:88)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Currently I'm not sure how to nail down the causing piece of code in my Application. Because of the type of App I can't show the corresponding source code. In general my steps to create a model in the scene is as follow.

* Get a hit result
* Create an Anchor from the hit result
* Create an AnchorNode from the Anchor
* Attache the AnchorNode to the scene
* Get a ViewRenderable from a pre created future object (reusability)
* Create a new Node and attache the ViewRenderable to it
* Set the AnchorNode as parent for the Node

So this is roughly the process in my app. 

Does the exception somehow looks familiar to someone and can give me some hints to nail down my problem? If neccessary I can provide some code snippeds but this will take some time to remove our buisiness logic.

**Comment by RGregat** [comment]
Has no one encountered a similar problem?

**Comment by tellypresence** [comment]
Looks like whatever you're doing is happening per frame (30-60fps?) instead of when the plane is tapped?  Could easily exhaust capacity for creating (expensive) renderable objects in a couple of seconds.

**Comment by RGregat** [comment]
Hmm, maybe it is a line I'm drawing. The line has to be synchronized with all drawn points in my scene. For that, I do on every onUpdate a check if the line has to be rebuild to match the drawn points. Well,  it is hard to tell, because the above Exception is everything what I get. It would be nice to know which part of my Code actually caused the above Exception. Any good ideas to better debug this error?
