### ISSUE TITLE
Error in Sceneform Tools 1.12.0

### ISSUE THREAD

**Issue by MostafaSolimanMO** [google-ar/sceneform-android-sdk#863]
I updated the plugin Google Sceneform Tools (Beta) to v.1.12.0, I started to get this error message and the viewer don't show any models

> java.lang.NullPointerException
	at com.google.ar.sceneform.plugin.viewer.SceneformSFAEditor.getState(SceneformSFAEditor.java:202)
	at com.intellij.openapi.fileEditor.impl.EditorWithProviderComposite.currentStateAsHistoryEntry(EditorWithProviderComposite.java:72)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.writeComposite(EditorsSplitters.java:231)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.writeWindow(EditorsSplitters.java:223)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.writePanel(EditorsSplitters.java:203)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.writeExternal(EditorsSplitters.java:170)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getState(FileEditorManagerImpl.java:1532)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getState(FileEditorManagerImpl.java:98)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponent(ComponentStoreImpl.kt:262)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreImpl.kt:199)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreWithExtraComponents.kt:89)
	at com.intellij.configurationStore.ComponentStoreImpl.doCreateSaveSessionManagerAndCommitComponents$intellij_platform_configurationStore_impl(ComponentStoreImpl.kt:155)
	at com.intellij.configurationStore.ComponentStoreImpl$createSaveSessionManagerAndSaveComponents$3.invokeSuspend(ComponentStoreImpl.kt:146)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by adrianofreires** [comment]
When I open an SFB file, my Android Studio suddenly closes. I am using Android Studio 3.5 

compileSdkVersion 28
    buildToolsVersion "29.0.2"

        minSdkVersion 27
        targetSdkVersion 28

**Comment by tpsiaki** [comment]
Thanks for the report - is this on Windows?

**Comment by adrianofreires** [comment]
Thank you for your help @tpsiaki . Yes! I'm using Windows 10. Before that, using Sceneform 1.11.1 (beta), but my grandle.app "com.google.ar.sceneform:core:1.11.0" I have a SFB file decoding problem, indicating what was the problem with UTF-8, even switching to another it did not encode correctly.

**Comment by vortice3D** [comment]
Hi **everybody**:

Continuous crashes of AS when opening the SFB viewer, has been not rare in my case from several Sceneform plugin versions.

Best regards.

**Comment by YinXiuYu** [comment]
I have the same issue，too. Android Studio suddenly closed when I open a SFB file with the sceneform plugin on Windows 10.

**Comment by eldivino87** [comment]
Me too. Same issue since 1.10.0 to the recent 1.12.0

**Comment by Y2JChamp** [comment]
is it possible to have a downgrade of the plug-in?

**Comment by dilberdillu** [comment]
@Y2JChamp https://plugins.jetbrains.com/plugin/10698-google-sceneform-tools-beta-/versions download the required version and install through disk by clicking gear icon in install window
