### ISSUE TITLE
Unable to upgrade from 1.11 to 1.12, crash on start

### ISSUE THREAD

**Issue by kewiany** [google-ar/sceneform-android-sdk#879]
Hi,

I wanna upgrade dependencies from 1.11.0 to 1.12.0 and I'm getting a crash once open a screen with AR staff.

2019-09-23 14:37:19.015 23377-23377/E/ArSceneView: Error loading libarsceneview_jni.so
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xxxPQ3NmGd9PwNeZYJgfjbZw==/base.apk"],nativeLibraryDirectories=[/data/app/xxxPQ3NmGd9PwNeZYJgfjbZw==/lib/arm64, /data/app/xxxPQ3NmGd9PwNeZYJgfjbZw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]] couldn't find "libarsceneview_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1660)
        at com.google.ar.sceneform.ArSceneView.reportEngineType(SourceFile:165)
        at com.google.ar.sceneform.ArSceneView.resumeSession(SourceFile:49)
        at com.google.ar.sceneform.ArSceneView.resume(SourceFile:39)
        at com.google.ar.sceneform.ux.BaseArFragment.start(BaseArFragment.java:507)
        at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:315)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2625)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2658)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2625)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:268)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:479)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:468)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:195)
        at android.app.Activity.performResume(Activity.java:7486)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4095)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4168)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3290)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7377)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by jpitkanen18** [comment]
Does your device also have the latest Google Play services for AR? Note that there is no x86 version of 1.12 in case you're using an emulator.

**Comment by chnouman** [comment]
I tried to upgrade     implementation "com.google.ar.sceneform.ux:sceneform-ux:" from 1.5.0 to 1.12.0 but I already know it has error: **Error loading libarsceneview_jni.so** so today 1.13.0 came I tried to update it and run but still faced the same error.

What work for me is manually update the ARCore services. what my app users are supposed to do?

**Comment by seop-archisketch** [comment]
@chnouman I used to use 1.12.0 version, and it worked fine. Then I uploaded it to 1.13.0 and I get this error. `E/ArSceneView: Error loading libarsceneview_jni.so`.  Since then, even rolling back the sceneform version to 1.12.0 won't let me run the app correctly.

**Comment by chnouman** [comment]
@seop-archisketch I had an issue with 1.12.0 that when ever I start the AR session it gives me this .so file error in the logcat but don't crash the app but it crashes randomly so I moved to 1.11.0 for production. Now today I just say that 1.13.0 came and gave it a try and faced the same error and even worst that It crashed the app in first atempt.

**Comment by seop-archisketch** [comment]
@chnouman does rolling back to 1.10.0 work now? It seems, for me, even rolling it back doesn't solve the issue any longer.  I get the error, it does NOT crash the app, but the camera is not visible.

**Comment by chnouman** [comment]
@seop-archisketch for me moving back from 1.12.0 to 1.11.0 works but I had to convert all models again with 1.11.0 plugin.

**Comment by chen-assert** [comment]
> Does your device also have the latest Google Play services for AR? Note that there is no x86 version of 1.12 in case you're using an emulator.

sorry, but may I ask what's your meanning? I also used the emulator and installed "Google_Play_Services_for_AR_1.13.0_x86_for_emulator.apk" but still met this problem.
Is you mean I should decrease the SDK version?

**Comment by chen-assert** [comment]
Well, after I decrease downgrade to v1.11.0, the problem seems dismissed, but unluckily, only the version>=v1.12.0 fix the issue "Sceneform Android Studio plugin compatibility with Android Studio 3.5 RC2".
So that means I can't modify and convert all models now.
I believe that must be something wrong.

**Comment by AmraKimmerian** [comment]
Same error.
implementation "com.google.ar.sceneform.ux:sceneform-ux:1.12.0"
classpath 'com.google.ar.sceneform:plugin:1.12.0'
Redmi Note 7, Android 9

Upgrade to version 1.13 get the same error and add another
ARCore-AuthenticationManager: Exception during AuthenticationManager construction: com.google.android.gms.common.GoogleApiAvailability
    java.lang.ClassNotFoundException: com.google.android.gms.common.GoogleApiAvailability
 at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at com.google.ar.persistence.AuthenticationManager.a(PG:72)
        at com.google.ar.persistence.AuthenticationManager.<init>(PG:4)
        at com.google.ar.persistence.AuthenticationManagerFactory.create(PG:3)
        at com.google.ar.core.Session.nativeCreateSessionAndWrapperWithFeatures(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:19)
        at com.google.ar.sceneform.ux.BaseArFragment.createSessionWithFeatures(BaseArFragment.java:391)
        at com.google.ar.sceneform.ux.BaseArFragment.createSession(BaseArFragment.java:380)
        at com.google.ar.sceneform.ux.BaseArFragment.initializeSession(BaseArFragment.java:354)
        at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:313)
        at com.example.artemka.fragments.CustomArFragment.onResume(CustomArFragment.java:66)

Downgrade to version 1.11 removes error "ArSceneView: Error loading libarsceneview_jni.so..." but still getting error "ARCore-AuthenticationManager: Exception during AuthenticationManager construction: com.google.android.gms.common.GoogleApiAvailability..."

**Comment by chen-assert** [comment]
Interesting, after all, I can run my application in a real android device, and it worked well.
But when I check the logcat, I find this error still occupy.(even the application still running and satisfy my expectation)
Is that means this exception is not the actual point which makes application crash?

implementation "com.google.ar.sceneform.ux:sceneform-ux:1.13.0"
classpath 'com.google.ar.sceneform:plugin:1.13.0'

this is my error log, but my application dont crash...

W/RenderThread: type=1400 audit(0.0:15687045): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=23156 scontext=u:r:untrusted_app:s0:c101,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc: Access denied finding property "vendor.debug.egl.changepixelformat"
E/ArSceneView: Error loading libarsceneview_jni.so
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/base.apk", zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_resources_apk.apk", zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/lib/arm64, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/base.apk!/lib/arm64-v8a, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.google.ar.sceneform.samples.augmentedimage-ZHU_P21yJ9MzNOO1oemxmA==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libarsceneview_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.google.ar.sceneform.ArSceneView.reportEngineType(SourceFile:232)
        at com.google.ar.sceneform.ArSceneView.resumeSession(SourceFile:51)
        at com.google.ar.sceneform.ArSceneView.resume(SourceFile:41)
        at com.google.ar.sceneform.ux.BaseArFragment.start(BaseArFragment.java:507)
        at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:315)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
E/ArSceneView:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
        at android.app.Activity.performResume(Activity.java:7330)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3921)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3961)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/native: session.cc:947 Entering Session::Resume.
I/native: data_manager.cc:212 Reseting and reinitializing filter from user request.

**Comment by cliveleehere** [comment]
> Is that means this exception is not the actual point which makes application crash?
Yeap, that's what i'm seeing as well

I believe the crash is actually caused by incompatible .sfb formats.

Try to re-import the 3d assets using the sceneform gradle plugin.
