### ISSUE TITLE
Everytime I get error UnSatisfiedLinkError

### ISSUE THREAD

**Issue by chnouman** [google-ar/sceneform-android-sdk#885]
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.visionx.loop-AHNmdqcimW2HipncKMzCZQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.visionx.loop-AHNmdqcimW2HipncKMzCZQ==/lib/arm64, /data/app/com.visionx.loop-AHNmdqcimW2HipncKMzCZQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libarsceneview_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.google.ar.sceneform.ArSceneView.reportEngineType(SourceFile:165)
        at com.google.ar.sceneform.ArSceneView.resumeSession(SourceFile:49)
        at com.google.ar.sceneform.ArSceneView.resume(SourceFile:39)
        at com.google.ar.sceneform.ux.BaseArFragment.start(BaseArFragment.java:507)
        at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:315)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2625)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:268)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:479)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:468)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:195)
        at android.app.Activity.performResume(Activity.java:7860)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3999)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4041)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1935)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7116)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
2019-10-02 15:35:04.747 1927-1927/com.visionx.loop E/ACameraMetadata: isNdkSupportedCapability: Unknonwn capability 10
```

**Comment by kewiany** [comment]
bump

**Comment by Komdosh** [comment]
still happens

**Comment by SyntaxError403** [comment]
Same here
