### ISSUE TITLE
cant load a valid gltf file

### ISSUE THREAD

**Issue by PerspectivesLab** [google-ar/sceneform-android-sdk#890]
While trying to load a valid gltf file generated in threejs i got the following error :
( the model loads perfectly in a gltf viewer, microsoft 3d viewer or other.. )

reproduce:
go to: https://threejs.org/editor/
create a cube, export it in gltf
load it in modelviewer / sceneform => face error
 

  java.util.concurrent.CompletionException: java.lang.RuntimeException: Mesh face is not a triangle
        at com.google.ar.sceneform.rendering.ak.run(SourceFile:39)
        at com.google.ar.sceneform.c.h.a(SourceFile:3)
        at com.google.common.s.a.br.run(SourceFile:7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: Mesh face is not a triangle
        at com.google.ar.sceneform.assets.Loader.nTryLoad(Native Method)
        at com.google.ar.sceneform.rendering.ak.run(SourceFile:4)
        at com.google.ar.sceneform.c.h.a(SourceFile:3) 
        at com.google.common.s.a.br.run(SourceFile:7) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2019-10-10 15:31:06.765 20971-20971/? E/ViewerActivity: Failed to load model.
    java.util.concurrent.CompletionException: java.lang.RuntimeException: Mesh face is not a triangle
        at com.google.ar.sceneform.rendering.ak.run(SourceFile:39)
        at com.google.ar.sceneform.c.h.a(SourceFile:3)
        at com.google.common.s.a.br.run(SourceFile:7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: Mesh face is not a triangle
        at com.google.ar.sceneform.assets.Loader.nTryLoad(Native Method)

**Comment by PerspectivesLab** [comment]
Actually it was working it was a cache issue browser side
