### ISSUE TITLE
Android app crash after Sceneform 1.13 update 

### ISSUE THREAD

**Issue by mbnsyqlo** [google-ar/sceneform-android-sdk#933]
Hey,

I was using previous version of "hellosceneform" application (sceneform version 1.9)  for learning but when I updated the sceneform version to 1.13 app is crashing. I have downloaded the latest sample of "hellosceneform" which is using sceneform 1.13 and I don't see any difference in code.

Can anyone please tell me what's the issue or am I missing something? 

I am using 
Android Studio 3.5.2
Gradle 3.4.1

1.13
https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/hellosceneform

**Comment by cliveleehere** [comment]
What's the crash you're seeing? stacktrace / logcat?

**Comment by mbnsyqlo** [comment]
> What's the crash you're seeing? stacktrace / logcat?

Hey, thanks for reply. I am not able to track it down and there is no message on. I was using the previous sample with the sceneform version 1.9 by  and I have updated the sceneform version and it crashed without any major error.

```12:20:33.691 3437-3437/? E/ArSceneView: Error loading libarsceneview_jni.so
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.ar.sceneform.samples.hellosceneform-pRD0HobJrX37hgk4tZP9TQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.ar.sceneform.samples.hellosceneform-pRD0HobJrX37hgk4tZP9TQ==/lib/arm64, /data/app/com.google.ar.sceneform.samples.hellosceneform-pRD0HobJrX37hgk4tZP9TQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libarsceneview_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.google.ar.sceneform.ArSceneView.reportEngineType(SourceFile:232)
        at com.google.ar.sceneform.ArSceneView.resumeSession(SourceFile:51)
        at com.google.ar.sceneform.ArSceneView.resume(SourceFile:41)
        at com.google.ar.sceneform.ux.BaseArFragment.start(BaseArFragment.java:507)
        at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:315)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
        at android.app.Activity.performResume(Activity.java:7987)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
 12:20:33.691 3437-3437/? I/native: session.cc:947 Entering Session::Resume.
```

I have seen another problem which is quite similar to this one I am sharing the link below.
https://github.com/google-ar/sceneform-android-sdk/issues/879

**Comment by cliveleehere** [comment]
This also sounds like an incompatible .sfb file. Try re-import the 3d asset, or manually run the `compileSceneformAssets` task in the module the 3d asset is located.

**Comment by mbnsyqlo** [comment]
yes I have already tried it but I didn't find anything. Even I have replaced the asset files (.obj, .mtl, .png) with hellosceneform files (1.1.3) but still not working.

**Comment by cliveleehere** [comment]
ah, i meant re-running the `compileSceneformAssets` gradle task so that a new .sfb file is generated.

**Comment by gitTronco** [comment]
downgrade the version to 1.12, and the plugin too
This version works fine, but when i upload to the 1.13 it works slowly, and finally crash not only the app, the device restart sometimes.

**Comment by mbnsyqlo** [comment]
> ah, i meant re-running the `compileSceneformAssets` gradle task so that a new .sfb file is generated.

thanks for the reply, I have to compile assets again for the newer version of sceneform and it works fine

**Comment by mbnsyqlo** [comment]
> downgrade the version to 1.12, and the plugin too
> This version works fine, but when i upload to the 1.13 it works slowly, and finally crash not only the app, the device restart sometimes.

thanks
