### ISSUE TITLE
my pro throws :couldn't find "libarsceneview_jni.so"

### ISSUE THREAD

**Issue by steven-gao** [google-ar/sceneform-android-sdk#936]
my pro in yesterday is well,but today throw errors.
please help me.
the more detail is follows:
2019-11-28 13:58:32.207 17722-17722/com.whyhow.xunguang E/ArSceneView: Error loading libarsceneview_jni.so
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.whyhow.xunguang-Gh73eEgV3Gs0coSIxAYuHQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.whyhow.xunguang-Gh73eEgV3Gs0coSIxAYuHQ==/lib/arm64, /data/app/com.whyhow.xunguang-Gh73eEgV3Gs0coSIxAYuHQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]] couldn't find "libarsceneview_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1672)
        at com.google.ar.sceneform.ArSceneView.reportEngineType(SourceFile:232)
        at com.google.ar.sceneform.ArSceneView.resumeSession(SourceFile:51)
        at com.google.ar.sceneform.ArSceneView.resume(SourceFile:41)
        at com.whyhow.xunguang.ar.SceneActivity.onResume(SceneActivity.kt:241)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:7614)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4412)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by cliveleehere** [comment]
I was getting this error as well. In my case, this error wasn't what was causing the crash, but the error did show up when the .sfb assets were generated from an incompatible plugin.
If you update the sceneform version, you might need to rerun the sceneform asset import.  Try manually running the gradle task `:compileSceneformAssets` for the module that the assets are in.
