### ISSUE TITLE
Geometry merging is unsupported when loading GLB.

### ISSUE THREAD

**Issue by hjeldin** [google-ar/sceneform-android-sdk#979]
Hi all,
i'm trying to load a GLB via google's [model-viewer](https://model-viewer.dev) and display it in AR.
I'm checking the correctness of the model with http://github.khronos.org/glTF-Validator/, and the Khronos validator says it's ok.
I also tried checking it against https://arvr.google.com/scene-viewer-preview and it returns the same error in the console.
The AR context crashes as soon as the model has finished downloading with the following error message:

> 01-30 17:13:40.088 14638 14638 D f       : Service connected
01-30 17:13:40.088 14638 14638 D f       : Service connected
01-30 17:13:40.108 17593 17605 D LoaderService: LoaderService created
01-30 17:13:40.123 17593 17605 I Filament: Filament library loaded.
01-30 17:13:40.128 14638 14638 D f       : Service create completed
01-30 17:13:40.131 14638 14638 D f       : Loader created
01-30 17:13:40.132 14638 17589 D an      : Loading stage: ADD_MISSING_FILES
01-30 17:13:40.134 17593 17606 E ImpView : Geometry merging is unsupported.
01-30 17:13:40.134 14638 17589 E ImpView : Received error from service: Geometry merging is unsupported.
01-30 17:13:40.136 14638 17589 D f       : Destroying
01-30 17:13:40.136 14638 17589 D f       : Stopping service
01-30 17:13:40.136 14638 17589 D f       : Calling unbindService
01-30 17:13:40.137 17593 17606 E ImpView : Failed to read 4 of 4 bytes, pipe closed
01-30 17:13:40.142 14638 17589 D f       : stopService completed
01-30 17:13:40.160 14638 14638 W an      : Load failed: https://s3.eu-central-1.amazonaws.com/cloud-myarstudio-public/LDQr0iOttAAfvQQ2LqVKmI2OrWpqBKy0HOhgW8GbbgLTbcFQls4wy1gukhU4GT9G/Playground/Products/0047425/default/0047425-configuration/export/glb/export.glb?link=https%3A%2F%2Fs3.eu-central-1.amazonaws.com%2Fcloud-myarstudio-utils%2Fviewer%2Findex.html%3Fb%3DLDQr0iOttAAfvQQ2LqVKmI2OrWpqBKy0HOhgW8GbbgLTbcFQls4wy1gukhU4GT9G%26p%3D0047425%26c%3D0047425-configuration%26u%3D3&title=
01-30 17:13:40.160 14638 14638 W an      : java.util.concurrent.CompletionException: java.lang.RuntimeException: Geometry merging is unsupported.
01-30 17:13:40.160 14638 14638 W an      : 	at com.google.ar.sceneform.rendering.aj.run(SourceFile:41)
01-30 17:13:40.160 14638 14638 W an      : 	at com.google.ar.sceneform.c.g.a(SourceFile:3)
01-30 17:13:40.160 14638 14638 W an      : 	at com.google.common.v.a.bq.run(SourceFile:9)
01-30 17:13:40.160 14638 14638 W an      : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-30 17:13:40.160 14638 14638 W an      : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-30 17:13:40.160 14638 14638 W an      : 	at java.lang.Thread.run(Thread.java:762)
01-30 17:13:40.160 14638 14638 W an      : Caused by: java.lang.RuntimeException: Geometry merging is unsupported.
01-30 17:13:40.160 14638 14638 W an      : 	at com.google.ar.sceneform.assets.Loader.nTryLoad(Native Method)
01-30 17:13:40.160 14638 14638 W an      : 	at com.google.ar.sceneform.rendering.aj.run(SourceFile:7)
01-30 17:13:40.160 14638 14638 W an      : 	... 5 more
01-30 17:13:40.161 14638 14638 E cb      : Unable to load Renderable registryId='https://s3.eu-central-1.amazonaws.com/cloud-myarstudio-public/LDQr0iOttAAfvQQ2LqVKmI2OrWpqBKy0HOhgW8GbbgLTbcFQls4wy1gukhU4GT9G/Playground/Products/0047425/default/0047425-configuration/export/glb/export.glb?link=https%3A%2F%2Fs3.eu-central-1.amazonaws.com%2Fcloud-myarstudio-utils%2Fviewer%2Findex.html%3Fb%3DLDQr0iOttAAfvQQ2LqVKmI2OrWpqBKy0HOhgW8GbbgLTbcFQls4wy1gukhU4GT9G%26p%3D0047425%26c%3D0047425-configuration%26u%3D3&title='
01-30 17:13:40.161 14638 14638 E cb      : java.util.concurrent.CompletionException: java.lang.RuntimeException: Geometry merging is unsupported.
01-30 17:13:40.161 14638 14638 E cb      : 	at com.google.ar.sceneform.rendering.aj.run(SourceFile:41)
01-30 17:13:40.161 14638 14638 E cb      : 	at com.google.ar.sceneform.c.g.a(SourceFile:3)
01-30 17:13:40.161 14638 14638 E cb      : 	at com.google.common.v.a.bq.run(SourceFile:9)
01-30 17:13:40.161 14638 14638 E cb      : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-30 17:13:40.161 14638 14638 E cb      : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-30 17:13:40.161 14638 14638 E cb      : 	at java.lang.Thread.run(Thread.java:762)
01-30 17:13:40.161 14638 14638 E cb      : Caused by: java.lang.RuntimeException: Geometry merging is unsupported.
01-30 17:13:40.161 14638 14638 E cb      : 	at com.google.ar.sceneform.assets.Loader.nTryLoad(Native Method)
01-30 17:13:40.161 14638 14638 E cb      : 	at com.google.ar.sceneform.rendering.aj.run(SourceFile:7)
01-30 17:13:40.161 14638 14638 E cb      : 	... 5 more
01-30 17:13:40.174 14638 14638 E fb      : Failed to load model.
01-30 17:13:40.174 14638 14638 E fb      : java.util.concurrent.CompletionException: java.util.concurrent.CompletionException: java.lang.RuntimeException: Geometry merging is unsupported.
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.ar.core.viewer.co.apply(SourceFile:1)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.ar.sceneform.c.b.a(SourceFile)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.b.a(SourceFile:3)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.c.run(SourceFile:22)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.aw.execute(SourceFile:3)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.d.b(SourceFile:73)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.d.a(SourceFile:72)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.d.b(SourceFile:169)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.h.run(SourceFile:21)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.aw.execute(SourceFile:3)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.d.b(SourceFile:73)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.d.a(SourceFile:72)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.d.b(SourceFile:169)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.ar.sceneform.c.l.a(SourceFile:16)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.ar.sceneform.c.h.a(SourceFile:2)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.bq.run(SourceFile:8)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.aw.execute(SourceFile:3)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.d.b(SourceFile:73)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.d.a(SourceFile:72)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.d.b(SourceFile:169)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.h.run(SourceFile:21)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.aw.execute(SourceFile:3)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.d.b(SourceFile:73)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.d.a(SourceFile:72)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.d.b(SourceFile:169)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.h.run(SourceFile:21)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.co.run(SourceFile:2)
01-30 17:13:40.174 14638 14638 E fb      : 	at android.os.Handler.handleCallback(Handler.java:751)
01-30 17:13:40.174 14638 14638 E fb      : 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-30 17:13:40.174 14638 14638 E fb      : 	at android.os.Looper.loop(Looper.java:154)
01-30 17:13:40.174 14638 14638 E fb      : 	at android.app.ActivityThread.main(ActivityThread.java:6692)
01-30 17:13:40.174 14638 14638 E fb      : 	at java.lang.reflect.Method.invoke(Native Method)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
01-30 17:13:40.174 14638 14638 E fb      : Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Geometry merging is unsupported.
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.ar.sceneform.rendering.aj.run(SourceFile:41)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.ar.sceneform.c.g.a(SourceFile:3)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.common.v.a.bq.run(SourceFile:9)
01-30 17:13:40.174 14638 14638 E fb      : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-30 17:13:40.174 14638 14638 E fb      : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-30 17:13:40.174 14638 14638 E fb      : 	at java.lang.Thread.run(Thread.java:762)
01-30 17:13:40.174 14638 14638 E fb      : Caused by: java.lang.RuntimeException: Geometry merging is unsupported.
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.ar.sceneform.assets.Loader.nTryLoad(Native Method)
01-30 17:13:40.174 14638 14638 E fb      : 	at com.google.ar.sceneform.rendering.aj.run(SourceFile:7)
01-30 17:13:40.174 14638 14638 E fb      : 	... 5 more

**Comment by hjeldin** [comment]
We managed to get a little deeper on this issue:

[bugReportGoogleSceneViewer.zip](https://github.com/google-ar/sceneform-android-sdk/files/4148901/bugReportGoogleSceneViewer.zip)

Attached you'll find 4 examples, 2 of which cause crashes when opened via the AR button on model-viewer.

It seems that the root cause is using only one mesh with multiple materials.
