### ISSUE TITLE
Crash after adding ~180 sceneForm cube primitives w/textView "cards"

### ISSUE THREAD

**Issue by stevesamknows** [google-ar/sceneform-android-sdk#98]
Simple app that adds SceneForm cube primitives w/"cards" (simple textView) as 
user explores AR space.  After ~180 objects added, consistently crashing.

Understand this may be classic "don't do that then" (though 180 cubes doesn't
seem excessive on modern OpenGL hardware), but a helpful error message
with suggestion would be very helpful...

Error trace:

2018-06-13 10:38:17.457 13976-13976/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.ar.sample, PID: 13976
    java.lang.IllegalArgumentException
        at android.view.Surface.nativeLockCanvas(Native Method)
        at android.view.Surface.lockCanvas(Surface.java:318)
        at com.google.ar.sceneform.rendering.RenderViewToSurfaceTexture.dispatchDraw(RenderViewToSurfaceTexture.java:107)
        at android.view.View.updateDisplayListIfDirty(View.java:18133)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by dsternfeld7** [comment]
Thanks for the report, can you include some information about how the textViews are created? Are you holding references to all these objects or is it possible some of them are being removed and garbage collected?

**Comment by romainguy** [comment]
180 cubes is fine, 180 `ViewRenderable` most likely isn't. Each `ViewRenderable` allocates quite a bit of memory and you're probably simply running out of memory.  You should reuse ViewRenderables as much as possible.

**Comment by stevesamknows** [comment]
On a related note, referring to the same scenario (original or modified solar system sample)
Say the user had tapped all the planets to add the textView "cards" -- now the user walks
backwards, away from the solar system.  When the user goes back say about 5 meters,
that seems like a reasonable place to toggle the visibility of the 
textView cards since the text would be very small at this distance -- what
are best practices via SceneForm for showing and hiding (i.e. GC'ing `ViewRenderable`s)
based on user distance (as opposed to when the renderables are completely offscreen)

Apologies for very basic questions; if it were possible to manage these sorts of memory/display
issues via SceneForm (instead of resorting to raw OpenGL as is done in some of the 
ARCore samples) would be beneficial since then wouldn't require devs with specialized 
OpenGL knowledge to extend and maintain the AR code.

Again, apologies for all the silly basic questions and thank you for your insightful comments

**Comment by romainguy** [comment]
One thing you can do right now is use bitmaps (you can use views to generate them) to create the cards (you would display a model of a quad/rectangle and use the bitmap as the texture). This works only if the cards' content is static but it would be a lot cheaper than using a ViewRenderable.

That said, it would be nice if Sceneform had APIs to query the visibility of an object in space in the current frame. Or Sceneform could implement ViewRenderable recycling.

**Comment by stevesamknows** [comment]
Thank you for following up.  IIUC the only way to do what you suggest is to introduce raw OpenGL
in order to add textured quads (since SceneForm models bake textures into the .sfb, and we won't
know the text content (and hence the texture) until runtime...

What's your opinion as regards mixing SceneForm and OpenGL?  If this isn't completely insane,
would be useful to continue using SceneForm for its primitives (e.g. cubes) and static textured
3D models, and just use OpenGL for textured quads to reduce usage of `ViewRenderable`s.

**Comment by romainguy** [comment]
You cannot mix OpenGL and Sceneform. The renderer purposefully hides the GL context away in a different thread. It would also cause problems in a future where a Vulkan backend is used instead for instance.

Procedural geometry (the ability to create geometry at runtime without going through a .sfb) is the way to go. There's also fundamentally no reason why Sceneform couldn't allow to bind textures dynamically at runtime. I'll take this up to the rest of the team to discuss.

**Comment by stevesamknows** [comment]
Thanks again Romain -- much appreciated
