### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ironmanromeo** [google-ar/sceneform-android-sdk#993]
Android Studio 3.6
Build #AI-192.7142.36.36.6200805, built on February 12, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: google-sceneform-tools

SceneForm plugin 1.15.0

"Import sceneform asset" command return:

java.lang.RuntimeException: java.lang.NoSuchMethodError: com.android.tools.idea.projectsystem.ProjectSystemSyncManager.syncProject(Lcom/android/tools/idea/projectsystem/ProjectSystemSyncManager$SyncReason;Z)Lcom/google/common/util/concurrent/ListenableFuture;
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:175)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:638)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:643)
	at com.google.ar.sceneform.plugin.actions.ui.GenerateSfbModel.promptAndRestoreGradleFile(GenerateSfbModel.java:231)
	at com.google.ar.sceneform.plugin.actions.ui.GenerateSfbModel.applyAndExecuteGradleRule(GenerateSfbModel.java:434)
	at com.google.ar.sceneform.plugin.actions.ui.GenerateSfbModel.access$000(GenerateSfbModel.java:52)
	at com.google.ar.sceneform.plugin.actions.ui.GenerateSfbModel$3.run(GenerateSfbModel.java:462)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.android.tools.idea.projectsystem.ProjectSystemSyncManager.syncProject(Lcom/android/tools/idea/projectsystem/ProjectSystemSyncManager$SyncReason;Z)Lcom/google/common/util/concurrent/ListenableFuture;
	at com.google.ar.sceneform.plugin.actions.ui.GenerateSfbModel.lambda$promptAndRestoreGradleFile$0(GenerateSfbModel.java:245)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:152)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dawcules** [comment]
Same error here. Also:

Error: java.lang.RuntimeException: java.lang.NoSuchMethodError: com.android.tools.idea.templates.recipe.RecipeExecutor.append(Ljava/io/File;Ljava/io/File;)

**Comment by elephantzhai** [comment]
Same error

**Comment by pauljervis** [comment]
Same error

**Comment by hshapley** [comment]
It seems like the Sceneform plugin 1.15 is incompatible with AS 3.6. Can you guys please fix this ASAP?

**Comment by KyleNordmann** [comment]
Exact same error. Make sure you folks send the error report when prompted in the IDE.

**Comment by ironmanromeo** [comment]
Same Error!!!!

**Comment by ironmanromeo** [comment]
Please send to this page your comments: https://developers.google.com/ar/develop/java/sceneform

**Comment by ironmanromeo** [comment]
A temporary solution: install Android Studio 3.5.1 + Sceneform 1.5, make sfb file, place in project in Android Studio 3.6.

**Comment by maheshwrn** [comment]
> A temporary solution: install Android Studio 3.5.1 + Sceneform 1.5, make sfb file, place in project in Android Studio 3.6.

I can't understand what you are trying to say. How can i use two android version in same pc?

**Comment by KyleNordmann** [comment]
@ironmanromeo could you do me a huge solid and provide some.guidance as to how to get AndroidStudio 3.5 back on my PC. Is the a way to downgrade or do I need to download it elsewhere? Thanks so much!

**Comment by ironmanromeo** [comment]
I decide to downgrade my project to 3.5.3.
https://developer.android.com/studio/archive
Gradle aligned to Android Studio version to 3.5.3.
Now I can build sfb without error. 
Google isn't looking good at the moment.
This is the first and last ArCore native project in Android Studio.
For example: Sceneform is nice to wrap the complexity of OpenGL, but now I'm studying how to make tiling and offset in fragment shader since Sceneform do not handle it. It doesn't make sense.
Xcode has a beautiful interface for 3D objects and let you configure all, tiling and offset too (obviously).

**Comment by KyleNordmann** [comment]
@ironmanromeo is the a specific way I need to align gradle to 3.5.3 or should that be happening automatically? -thx again :)

**Comment by ironmanromeo** [comment]
I did try Android Studio 3.6.1 with Gradle 3.5.3 without success, so I downloaded from Google Android Studio 3.5.3, aligned Gradle with 3.5.3 and updated project.

Now I can generate SFB without errors.

**Comment by KyleNordmann** [comment]
so I managed to create the sfa/sfb by using an older version of Android Studio but when I run the app all that loads is the shadow of the model and not the model itself... yeah um.. any ideas?

**Comment by ironmanromeo** [comment]
Downgrade all the project to 3.5.1

Inviato da iPhone

**Comment by linahg** [comment]
Please fix it!
