### ISSUE TITLE
Problem with bones after converting from FBX to SFB - model deformed

### ISSUE THREAD

**Issue by Dosssik** [google-ar/sceneform-android-sdk#995]
Hi there!
We experiencing a problem with the model conversion. We have a model in FBX format with 230 bones and some build-in skeleton animations. Everything looks and works fine before converting it to SFB.

But after converting the model is partly deformed. Animations work fine but the form of the model is broken. 

There are no errors in the log during converting.
We tried to change different export parameters - nothing helped. Also tried to convert on different Sceneform plugin version - no difference. The only thing to avoid deformation - remove all bones, then everything looks fine. But it's unacceptable for us because we need animations, based on bones.

Screenshot before converting:
<img width="526" alt="Screenshot 2020-02-27 at 14 31 53" src="https://user-images.githubusercontent.com/12698708/75431012-0d249f80-596e-11ea-8479-591326052839.png">

Screenshot after converting, in the app:
<img width="405" alt="Screenshot 2020-02-27 at 14 32 22" src="https://user-images.githubusercontent.com/12698708/75431075-1f9ed900-596e-11ea-8949-916bc761cb39.png">

Did anyone face the same problems? Any advice about how to overcome it?
Thank you

**Comment by ironmanromeo** [comment]
Please let me know what version of Android Studio and SceneForm plugin you are using. We get and error: 

java.lang.RuntimeException: java.lang.NoSuchMethodError: com.android.tools.idea.projectsystem.ProjectSystemSyncManager.syncProject(Lcom/android/tools/idea/projectsystem/ProjectSystemSyncManager$SyncReason;Z)Lcom/google/common/util/concurrent/ListenableFuture;
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:175)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:638)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:643)
	at com.google.ar.sceneform.plugin.actions.ui.GenerateSfbModel.promptAndRestoreGradleFile(GenerateSfbModel.java:231)
	at com.google.ar.sceneform.plugin.actions.ui.GenerateSfbModel.applyAndExecuteGradleRule(GenerateSfbModel.java:434)
	at com.google.ar.sceneform.plugin.actions.ui.GenerateSfbModel.access$000(GenerateSfbModel.java:52)
	at com.google.ar.sceneform.plugin.actions.ui.GenerateSfbModel$3.run(GenerateSfbModel.java:462)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.android.tools.idea.projectsystem.ProjectSystemSyncManager.syncProject(Lcom/android/tools/idea/projectsystem/ProjectSystemSyncManager$SyncReason;Z)Lcom/google/common/util/concurrent/ListenableFuture;
	at com.google.ar.sceneform.plugin.actions.ui.GenerateSfbModel.lambda$promptAndRestoreGradleFile$0(GenerateSfbModel.java:245)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:152)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



13:55	Error: java.lang.RuntimeException: java.lang.NoSuchMethodError: com.android.tools.idea.templates.recipe.RecipeExecutor.append(Ljava/io/File;Ljava/io/File;)V


java.lang.RuntimeException: java.lang.NoSuchMethodError: com.android.tools.idea.projectsystem.ProjectSystemSyncManager.syncProject(Lcom/android/tools/idea/projectsystem/ProjectSystemSyncManager$SyncReason;Z)Lcom/google/common/util/concurrent/ListenableFuture;


el.promptAndRestoreGradleFile

**Comment by sqaaa** [comment]
We're using 
Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3

and plugin version is 1.14.0

**Comment by sqaaa** [comment]
Little update, we found possible adhoc solution for solving this issue. So we guess that sceneform get wrong bones weights and so far this points goes to the coordinates center, therefore we placed model lower the center and bingo, liquid faces are gone (or less visible to us)
![no_liquid_faces](https://user-images.githubusercontent.com/11176780/75965503-f7692a00-5ed9-11ea-87fa-ddacae35d13a.gif)

but if we return it back up of the center we have liquid faces again 
![liquid](https://user-images.githubusercontent.com/11176780/75965730-444d0080-5eda-11ea-80ab-19de09325afd.gif)


Could you guys spill something about this?
